# Generated by Django 6.0.8 on 2026-09-06 21:17

import apps.reservations.models
import apps.reservations.validators
import apps.user.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0029_office_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('category', models.CharField(choices=[('accessibility', 'Accessibility'), ('audio_visual', 'Audio and visual'), ('connectivity', 'Connectivity'), ('furnishings', 'Furnishings'), ('food_beverage', 'Food and beverage'), ('privacy', 'Privacy'), ('other', 'Other')], max_length=32, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'space amenity',
                'verbose_name_plural': 'space amenities',
                'ordering': ['display_order', 'name', 'pk'],
                'indexes': [models.Index(fields=['is_active', 'category', 'display_order'], name='rsv_amenity_catalog_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='rsv_amenity_requires_code'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='rsv_amenity_requires_name')],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('space_type', models.CharField(choices=[('conference_room', 'Conference room'), ('meeting_room', 'Meeting room'), ('training_room', 'Training room'), ('private_office', 'Private office'), ('coworking_area', 'Coworking area'), ('event_space', 'Event space'), ('studio', 'Studio'), ('other', 'Other')], max_length=32, verbose_name='space type')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='capacity')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=240, verbose_name='location')),
                ('access_instructions', models.TextField(blank=True, help_text='Sensitive; omit unless the reader has the field permission.', verbose_name='internal access instructions')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', max_length=16, verbose_name='status')),
                ('is_reservable', models.BooleanField(default=True, verbose_name='reservable')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('minimum_duration_minutes', models.PositiveIntegerField(default=30, verbose_name='minimum duration in minutes')),
                ('maximum_duration_minutes', models.PositiveIntegerField(default=480, verbose_name='maximum duration in minutes')),
                ('booking_horizon_days', models.PositiveIntegerField(default=90, verbose_name='booking horizon in days')),
                ('minimum_notice_minutes', models.PositiveIntegerField(default=0, verbose_name='minimum notice in minutes')),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0, verbose_name='buffer before in minutes')),
                ('buffer_after_minutes', models.PositiveIntegerField(default=0, verbose_name='cleanup buffer after in minutes')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='requires approval')),
                ('cancellation_cutoff_minutes', models.PositiveIntegerField(default=0, verbose_name='cancellation cutoff in minutes')),
                ('recurrence_policy', models.CharField(choices=[('none', 'Recurring bookings not allowed'), ('weekly', 'Weekly recurrence allowed'), ('daily_or_weekly', 'Daily or weekly recurrence allowed')], default='none', max_length=24, verbose_name='recurrence policy')),
                ('maximum_recurrence_occurrences', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum recurrence occurrences')),
                ('booking_history_started_at', models.DateTimeField(blank=True, help_text='Set by the booking service on the first booking; ordinary office transfers then fail closed.', null=True, verbose_name='booking history started at')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='retired at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_spaces_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservable_spaces', to='user.office', verbose_name='owning office')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_spaces_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'reservable space',
                'verbose_name_plural': 'reservable spaces',
                'ordering': ['display_order', 'name', 'pk'],
                'permissions': (('view_spaces', 'Can view scoped office spaces'), ('manage_spaces', 'Can manage scoped office spaces'), ('manage_space_schedules', 'Can manage scoped space schedules and exceptions'), ('view_space_sensitive', 'Can view access instructions and internal exception details')),
            },
        ),
        migrations.CreateModel(
            name='SpaceAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=160, verbose_name='notes')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='space_assignments', to='reservations.amenity')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_assignments', to='reservations.space')),
            ],
            options={
                'ordering': ['display_order', 'amenity__display_order', 'amenity__name'],
            },
        ),
        migrations.AddField(
            model_name='space',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='spaces', through='reservations.SpaceAmenity', to='reservations.amenity'),
        ),
        migrations.CreateModel(
            name='SpaceAvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('kind', models.CharField(choices=[('holiday', 'Holiday'), ('maintenance', 'Maintenance'), ('closure', 'Closure'), ('admin_hold', 'Administrative hold')], max_length=20, verbose_name='kind')),
                ('starts_at', models.DateTimeField(verbose_name='starts at')),
                ('ends_at', models.DateTimeField(verbose_name='ends at')),
                ('reason', models.CharField(max_length=500, verbose_name='reason')),
                ('visibility', models.CharField(choices=[('public', 'Visible to agents'), ('internal', 'Internal only')], default='internal', max_length=16, verbose_name='visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_space_exceptions_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_exceptions', to='reservations.space', verbose_name='space')),
            ],
            options={
                'verbose_name': 'space availability exception',
                'verbose_name_plural': 'space availability exceptions',
                'ordering': ['starts_at', 'ends_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SpaceOfficeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preserves_booking_history', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=500, verbose_name='reason')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='performed at')),
                ('from_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_space_transfers_from', to='user.office')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_space_transfers_performed', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_transfers', to='reservations.space', verbose_name='space')),
                ('to_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_space_transfers_to', to='user.office')),
            ],
            options={
                'ordering': ['-performed_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SpacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('file', models.ImageField(max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.reservations.models.space_photo_upload_to, validators=[apps.reservations.validators.validate_space_photo], verbose_name='photo')),
                ('alt_text', models.CharField(max_length=240, verbose_name='alternative text')),
                ('is_public', models.BooleanField(default=True, help_text='The object remains in protected storage in every state.', verbose_name='visible to agents')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_space_photos_created', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='reservations.space', verbose_name='space')),
            ],
            options={
                'ordering': ['display_order', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday')),
                ('starts_at', models.TimeField(verbose_name='starts at')),
                ('ends_at', models.TimeField(verbose_name='ends at')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='reservations.space', verbose_name='space')),
            ],
            options={
                'verbose_name': 'weekly space availability',
                'verbose_name_plural': 'weekly space availability',
                'ordering': ['weekday', 'starts_at', 'display_order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='spaceamenity',
            index=models.Index(fields=['amenity', 'space'], name='rsv_space_amenity_filter_idx'),
        ),
        migrations.AddConstraint(
            model_name='spaceamenity',
            constraint=models.UniqueConstraint(fields=('space', 'amenity'), name='rsv_space_amenity_unique'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['owner_office', 'status', 'space_type'], name='rsv_space_office_state_type'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['owner_office', 'is_reservable', 'display_order'], name='rsv_space_office_res_order'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='rsv_space_requires_name'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='rsv_space_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_duration_minutes__gte', 1)), name='rsv_space_min_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_duration_minutes__gte', 1)), name='rsv_space_max_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_duration_minutes__gte', models.F('minimum_duration_minutes'))), name='rsv_space_duration_order'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(('booking_horizon_days__gte', 1)), name='rsv_space_horizon_positive'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_notice_minutes__gte', 0)), name='rsv_space_notice_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(('buffer_before_minutes__gte', 0)), name='rsv_space_buffer_before_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(('buffer_after_minutes__gte', 0)), name='rsv_space_buffer_after_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(('cancellation_cutoff_minutes__gte', 0)), name='rsv_space_cancel_cutoff_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(('is_reservable', False), ('status', 'active'), _connector='OR'), name='rsv_space_reservable_when_active'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('retired_at__isnull', False), ('status', 'retired')), models.Q(models.Q(('status', 'retired'), _negated=True), ('retired_at__isnull', True)), _connector='OR'), name='rsv_space_retired_at_matches'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('maximum_recurrence_occurrences__isnull', True), ('recurrence_policy', 'none')), models.Q(models.Q(('recurrence_policy', 'none'), _negated=True), ('maximum_recurrence_occurrences__gte', 2)), _connector='OR'), name='rsv_space_recurrence_consistent'),
        ),
        migrations.AddIndex(
            model_name='spaceavailabilityexception',
            index=models.Index(fields=['space', 'starts_at', 'ends_at'], name='rsv_exception_space_time'),
        ),
        migrations.AddIndex(
            model_name='spaceavailabilityexception',
            index=models.Index(fields=['space', 'kind', 'starts_at'], name='rsv_exception_kind_time'),
        ),
        migrations.AddConstraint(
            model_name='spaceavailabilityexception',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='rsv_exception_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='spaceavailabilityexception',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='rsv_exception_requires_reason'),
        ),
        migrations.AddIndex(
            model_name='spaceofficetransfer',
            index=models.Index(fields=['space', '-performed_at'], name='rsv_space_transfer_history'),
        ),
        migrations.AddConstraint(
            model_name='spaceofficetransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_office', models.F('to_office')), _negated=True), name='rsv_space_transfer_changes_office'),
        ),
        migrations.AddConstraint(
            model_name='spaceofficetransfer',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='rsv_space_transfer_reason'),
        ),
        migrations.AddIndex(
            model_name='spacephoto',
            index=models.Index(fields=['space', 'is_public', 'display_order'], name='rsv_space_photo_listing_idx'),
        ),
        migrations.AddConstraint(
            model_name='spacephoto',
            constraint=models.CheckConstraint(condition=models.Q(('alt_text', ''), _negated=True), name='rsv_space_photo_requires_alt'),
        ),
        migrations.AddIndex(
            model_name='weeklyavailability',
            index=models.Index(fields=['space', 'weekday', 'starts_at', 'ends_at'], name='rsv_weekly_space_day_time'),
        ),
        migrations.AddConstraint(
            model_name='weeklyavailability',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='rsv_weekly_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='weeklyavailability',
            constraint=models.UniqueConstraint(fields=('space', 'weekday', 'starts_at', 'ends_at'), name='rsv_weekly_interval_unique'),
        ),
    ]
