# Generated by Django 6.0.8 on 2026-09-06 21:18

from django.db import migrations

ROLE_CODES = (
    "system_admin",
    "principal_broker",
    "broker_admin",
    "regional_manager",
    "regional_admin",
    "branch_manager",
    "branch_admin",
)

PERMISSION_CODES = (
    "view_spaces",
    "manage_spaces",
    "manage_space_schedules",
    "view_space_sensitive",
)


def _ensure_reservation_permissions(apps) -> None:
    from django.apps import apps as global_apps
    from django.contrib.auth.management import create_permissions

    app_config = global_apps.get_app_config("reservations")
    if app_config.models_module is None:
        app_config.models_module = app_config.module
    create_permissions(app_config, apps=apps, verbosity=0)


def grant(apps, schema_editor):
    from apps.user.roles import ROLE_BY_KEY

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    _ensure_reservation_permissions(apps)
    permissions = list(
        Permission.objects.filter(
            content_type__app_label="reservations",
            codename__in=PERMISSION_CODES,
        )
    )
    for role_code in ROLE_CODES:
        definition = ROLE_BY_KEY.get(role_code)
        if definition is None:
            continue
        group = Group.objects.filter(name=definition.group_name).first()
        if group is not None:
            group.permissions.add(*permissions)


def ungrant(apps, schema_editor):
    from apps.user.roles import ROLE_BY_KEY

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    permissions = list(
        Permission.objects.filter(
            content_type__app_label="reservations",
            codename__in=PERMISSION_CODES,
        )
    )
    for role_code in ROLE_CODES:
        definition = ROLE_BY_KEY.get(role_code)
        if definition is None:
            continue
        group = Group.objects.filter(name=definition.group_name).first()
        if group is not None:
            group.permissions.remove(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
        ("user", "0029_office_timezone"),
    ]

    operations = [migrations.RunPython(grant, ungrant)]
