# Generated by Django 6.0.8 on 2026-08-30 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0027_feedback_triage_role_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('group', models.CharField(choices=[('company', 'Company tools'), ('association', 'Association & MLS'), ('marketing', 'Profiles & marketing')], max_length=20, verbose_name='group')),
                ('provisioning', models.CharField(choices=[('self_serve', 'You set this up'), ('onest', 'oNEST sets this up for you'), ('both', 'You sign up, then oNEST activates it')], default='onest', max_length=16, verbose_name='provisioning')),
                ('open_url', models.URLField(blank=True, max_length=500, verbose_name='open url')),
                ('help_url', models.URLField(blank=True, max_length=500, verbose_name='vendor help url')),
                ('setup_steps', models.JSONField(blank=True, default=list, verbose_name='setup steps')),
                ('contact_label', models.CharField(blank=True, max_length=120, verbose_name='who to contact')),
                ('request_path', models.CharField(blank=True, max_length=200, verbose_name='request path')),
                ('company_wide', models.BooleanField(default=True, help_text='Off means this tool applies only to the offices and regions named below — an MLS or a state association, typically.', verbose_name='applies everywhere')),
                ('is_required', models.BooleanField(default=True, verbose_name='required')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'onboarding tool',
                'verbose_name_plural': 'onboarding tools',
                'ordering': ['group', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['group', 'sort_order'], name='onbtool_group_order_idx'), models.Index(fields=['is_active'], name='onbtool_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='onboarding_tool_requires_name'), models.CheckConstraint(condition=models.Q(('setup_steps', []), ('contact_label', ''), _negated=True), name='onboarding_tool_needs_steps_or_a_contact')],
            },
        ),
        migrations.CreateModel(
            name='AgentToolStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('ready', 'Ready'), ('blocked', 'Blocked'), ('not_applicable', 'Not needed')], default='not_started', max_length=20, verbose_name='state')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='ready at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_statuses', to=settings.AUTH_USER_MODEL, verbose_name='agent')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tool_statuses', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_statuses', to='onboarding_tools.onboardingtool', verbose_name='tool')),
            ],
            options={
                'verbose_name': 'agent tool status',
                'verbose_name_plural': 'agent tool statuses',
                'ordering': ['tool__group', 'tool__sort_order'],
                'indexes': [models.Index(fields=['agent', 'state'], name='agenttool_agent_state_idx'), models.Index(fields=['tool', 'state'], name='agenttool_tool_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'tool'), name='agent_tool_status_unique'), models.CheckConstraint(condition=models.Q(models.Q(('ready_at__isnull', False), ('state', 'ready')), models.Q(models.Q(('state', 'ready'), _negated=True), ('ready_at__isnull', True)), _connector='OR'), name='agent_tool_ready_at_matches_state')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingToolOfficeAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_descendants', models.BooleanField(default=True, verbose_name='include descendants')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tool_audiences', to='user.office', verbose_name='office')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_audiences', to='onboarding_tools.onboardingtool', verbose_name='tool')),
            ],
            options={
                'verbose_name': 'onboarding tool audience',
                'verbose_name_plural': 'onboarding tool audiences',
                'ordering': ['office__sort_order', 'office__name'],
                'constraints': [models.UniqueConstraint(fields=('tool', 'office'), name='onboarding_tool_audience_unique')],
            },
        ),
    ]
