# Generated by Django 6.0.8 on 2026-09-12 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_tools', '0002_seed_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoolstatus',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invitation sent at'),
        ),
        migrations.AddField(
            model_name='agenttoolstatus',
            name='invitation_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tool_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invitation sent by'),
        ),
        migrations.AddField(
            model_name='agenttoolstatus',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='requested at'),
        ),
        migrations.AlterField(
            model_name='agenttoolstatus',
            name='state',
            field=models.CharField(choices=[('not_started', 'Not started'), ('requested', 'Requested'), ('invitation_sent', 'Invitation sent'), ('in_progress', 'In progress'), ('ready', 'Ready'), ('blocked', 'Blocked'), ('not_applicable', 'Not needed')], default='not_started', max_length=20, verbose_name='state'),
        ),
        migrations.AddConstraint(
            model_name='agenttoolstatus',
            constraint=models.CheckConstraint(condition=models.Q(('invitation_sent_by__isnull', True), ('invitation_sent_at__isnull', False), _connector='OR'), name='agent_tool_invitation_sender_has_time'),
        ),
        migrations.AddConstraint(
            model_name='agenttoolstatus',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'invitation_sent'), _negated=True), ('invitation_sent_at__isnull', False), _connector='OR'), name='agent_tool_invitation_sent_has_time'),
        ),
    ]
