# Generated by Django 6.0.8 on 2026-09-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_tools', '0004_migrate_legacy_tool_setups'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoolstatus',
            name='agent_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='agent confirmed at'),
        ),
    ]
