# Generated by Django 6.0.8 on 2026-08-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperationsPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_users", "Can view scoped users"),
                    ("view_new_agents", "Can view scoped new agents"),
                    ("add_users", "Can add users"),
                    ("assign_user_roles", "Can assign user roles"),
                    ("view_agent_contracts", "Can view scoped agent contracts"),
                    ("view_transactions", "Can view scoped transactions"),
                    ("view_inventory", "Can view scoped inventory"),
                    ("view_reservations", "Can view scoped reservations"),
                    ("manage_announcements", "Can manage announcements"),
                    ("manage_training", "Can manage training"),
                    ("manage_documents", "Can manage documents"),
                    ("view_compliance", "Can view scoped compliance items"),
                    ("view_feedback", "Can view scoped feedback"),
                    ("view_platform_tasks", "Can view sanitized platform task status"),
                    ("manage_offices", "Can manage scoped offices"),
                    ("view_it_support", "Can view scoped IT support requests"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
