# Generated by Django 6.0.8 on 2026-08-20 02:47

from django.db import migrations


CODENAME = "manage_new_agent_onboarding"
GROUPS = ("Admins", "Region Managers", "Branch Managers")


def grant_permission(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    content_type, _created = ContentType.objects.get_or_create(
        app_label="web", model="operationspermission"
    )
    permission, _created = Permission.objects.get_or_create(
        content_type=content_type,
        codename=CODENAME,
        defaults={"name": "Can manage scoped new-agent onboarding"},
    )
    for name in GROUPS:
        group, _created = Group.objects.get_or_create(name=name)
        group.permissions.add(permission)


def revoke_permission(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    permission = Permission.objects.filter(
        content_type__app_label="web",
        content_type__model="operationspermission",
        codename=CODENAME,
    ).first()
    if permission is None:
        return
    for group in Group.objects.filter(name__in=GROUPS):
        group.permissions.remove(permission)


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("web", "0004_alter_operationspermission_options"),
    ]

    operations = [migrations.RunPython(grant_permission, revoke_permission)]
