# Generated by Django 6.0.8 on 2026-08-20 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_brokerage_role_catalog'),
        ('web', '0005_grant_new_agent_onboarding_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationspermission',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_users', 'Can view scoped users'), ('view_new_agents', 'Can view scoped new agents'), ('manage_new_agent_onboarding', 'Can manage scoped new-agent onboarding'), ('add_users', 'Can add users'), ('assign_user_roles', 'Can assign user roles'), ('view_agent_contracts', 'Can view scoped agent contracts'), ('view_transactions', 'Can view scoped transactions'), ('view_inventory', 'Can view scoped inventory'), ('view_reservations', 'Can view scoped reservations'), ('manage_announcements', 'Can manage announcements'), ('manage_training', 'Can manage training'), ('manage_documents', 'Can manage documents'), ('view_compliance', 'Can view scoped compliance items'), ('view_feedback', 'Can view scoped feedback'), ('view_platform_tasks', 'Can view sanitized platform task status'), ('manage_offices', 'Can manage scoped offices'), ('view_it_support', 'Can view scoped IT support requests'), ('manage_quick_access', 'Can manage scoped Quick Access links'), ('manage_company_quick_access', 'Can manage company-wide Quick Access links'))},
        ),
        migrations.CreateModel(
            name='QuickAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_key', models.SlugField(help_text='Permanent identity used by audit records and integrations. Cannot be changed once the link exists.', max_length=64, unique=True, verbose_name='stable key')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('destination_type', models.CharField(choices=[('external_url', 'External URL'), ('internal_route', 'Internal route')], default='external_url', max_length=32, verbose_name='destination type')),
                ('destination_value', models.CharField(help_text='An https:// URL, or the key of an allowlisted internal destination.', max_length=500, verbose_name='destination')),
                ('icon', models.CharField(default='app-window', help_text='Key of an approved mark shipped by the frontend.', max_length=32, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower sorts first. Positions may repeat; ties break by name so routine reordering never has to renumber the whole panel.', verbose_name='sort order')),
                ('publish_start_at', models.DateTimeField(blank=True, null=True, verbose_name='publish from')),
                ('publish_end_at', models.DateTimeField(blank=True, null=True, verbose_name='publish until')),
                ('sso_capability', models.CharField(choices=[('none', 'No single sign-on'), ('microsoft_entra', 'Microsoft Entra ID'), ('saml', 'SAML'), ('oidc', 'OpenID Connect')], default='none', max_length=32, verbose_name='single sign-on')),
                ('integration_health', models.CharField(choices=[('unknown', 'Not monitored'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('offline', 'Offline')], default='unknown', max_length=32, verbose_name='integration health')),
                ('setup_behavior', models.CharField(choices=[('none', 'No setup step'), ('self_service', 'Agent signs in directly'), ('request_access', 'Access must be requested'), ('provisioned', 'Provisioned during onboarding')], default='self_service', max_length=32, verbose_name='setup behaviour')),
                ('company_wide', models.BooleanField(default=False, help_text='Ignore office audience rows and show this to every office.', verbose_name='visible company-wide')),
                ('owner_scope', models.CharField(choices=[('company', 'Company'), ('scoped', 'Office or region')], default='scoped', max_length=16, verbose_name='owner scope')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quick_access_links', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_quick_access_links', to='user.office', verbose_name='owning office')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quick_access_links', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'quick access link',
                'verbose_name_plural': 'quick access links',
                'ordering': ['sort_order', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QuickAccessLinkOfficeAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_descendants', models.BooleanField(default=True, verbose_name='include descendants')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_audiences', to='web.quickaccesslink', verbose_name='link')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_access_audiences', to='user.office', verbose_name='office')),
            ],
            options={
                'verbose_name': 'quick access office audience',
                'verbose_name_plural': 'quick access office audiences',
                'ordering': ['office__sort_order', 'office__name'],
            },
        ),
        migrations.CreateModel(
            name='QuickAccessLinkRoleAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(max_length=64, verbose_name='role')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_audiences', to='web.quickaccesslink', verbose_name='link')),
            ],
            options={
                'verbose_name': 'quick access role audience',
                'verbose_name_plural': 'quick access role audiences',
                'ordering': ['role_code'],
            },
        ),
        migrations.AddIndex(
            model_name='quickaccesslink',
            index=models.Index(fields=['is_archived', 'is_active', 'sort_order'], name='web_qal_live_order'),
        ),
        migrations.AddIndex(
            model_name='quickaccesslink',
            index=models.Index(fields=['publish_start_at', 'publish_end_at'], name='web_qal_window'),
        ),
        migrations.AddIndex(
            model_name='quickaccesslink',
            index=models.Index(fields=['owner_scope'], name='web_qal_owner_scope'),
        ),
        migrations.AddConstraint(
            model_name='quickaccesslink',
            constraint=models.CheckConstraint(condition=models.Q(('publish_end_at__isnull', True), ('publish_start_at__isnull', True), ('publish_end_at__gt', models.F('publish_start_at')), _connector='OR'), name='web_qal_publish_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='quickaccesslink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_scope', 'scoped'), _negated=True), ('company_wide', False), _connector='OR'), name='web_qal_company_wide_is_company_owned'),
        ),
        migrations.AddConstraint(
            model_name='quickaccesslinkofficeaudience',
            constraint=models.UniqueConstraint(fields=('link', 'office'), name='web_qal_office_unique'),
        ),
        migrations.AddConstraint(
            model_name='quickaccesslinkroleaudience',
            constraint=models.UniqueConstraint(fields=('link', 'role_code'), name='web_qal_role_unique'),
        ),
    ]
