# Generated by Django 6.0.8 on 2026-08-21 01:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0019_grant_account_state_permission"),
        ("web", "0007_quick_access_permissions_and_seed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickAccessLinkClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_stable_key",
                    models.SlugField(max_length=64, verbose_name="link key"),
                ),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("external_url", "External URL"),
                            ("internal_route", "Internal route"),
                        ],
                        max_length=32,
                        verbose_name="destination type",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="occurred at"
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clicks",
                        to="web.quickaccesslink",
                        verbose_name="link",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quick_access_clicks",
                        to="user.office",
                        verbose_name="office",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quick_access_clicks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "quick access click",
                "verbose_name_plural": "quick access clicks",
                "ordering": ["-occurred_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["link_stable_key", "occurred_at"],
                        name="web_qac_key_time",
                    ),
                    models.Index(fields=["occurred_at"], name="web_qac_time"),
                ],
            },
        ),
    ]
