# Generated by Django 6.0.8 on 2026-08-23 11:42

import apps.user.storage
import apps.web.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

PERMISSION_NAMES = {
    "view_reports": "Can view the operational reports catalog",
    "export_reports": "Can export operational reports",
}

VIEW_GROUPS = (
    "Admins",
    "Principal Broker",
    "Broker Admin",
    "Region Managers",
    "Regional Admin",
    "Branch Managers",
    "Branch Admin",
    "Users",
    "Transaction Coordinator",
    "Regional Transaction Coordinator",
    "Accountant",
    "Compliance",
)

EXPORT_GROUPS = (
    "Admins",
    "Principal Broker",
    "Broker Admin",
    "Region Managers",
    "Regional Admin",
    "Branch Managers",
    "Branch Admin",
    "Transaction Coordinator",
    "Regional Transaction Coordinator",
    "Accountant",
    "Compliance",
)


def grant_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    content_type, _ = ContentType.objects.get_or_create(
        app_label="web",
        model="operationspermission",
    )
    permissions = {}
    for codename, name in PERMISSION_NAMES.items():
        permission, _ = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permissions[codename] = permission
    for group_name in VIEW_GROUPS:
        group, _ = Group.objects.get_or_create(name=group_name)
        group.permissions.add(permissions["view_reports"])
    for group_name in EXPORT_GROUPS:
        group, _ = Group.objects.get_or_create(name=group_name)
        group.permissions.add(permissions["export_reports"])


def revoke_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    permissions = Permission.objects.filter(
        content_type__app_label="web",
        content_type__model="operationspermission",
        codename__in=PERMISSION_NAMES,
    )
    for group in Group.objects.all():
        group.permissions.remove(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_alter_operationspermission_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationspermission",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("view_users", "Can view scoped users"),
                    ("view_new_agents", "Can view scoped new agents"),
                    (
                        "manage_new_agent_onboarding",
                        "Can manage scoped new-agent onboarding",
                    ),
                    ("add_users", "Can add users"),
                    ("assign_user_roles", "Can assign user roles"),
                    ("view_agent_contracts", "Can view scoped agent contracts"),
                    ("view_transactions", "Can view scoped transactions"),
                    ("view_inventory", "Can view scoped inventory"),
                    ("view_reservations", "Can view scoped reservations"),
                    ("manage_announcements", "Can manage announcements"),
                    (
                        "publish_announcements",
                        "Can publish, schedule, and archive announcements",
                    ),
                    ("pin_announcements", "Can pin announcements"),
                    ("manage_training", "Can manage training"),
                    ("manage_documents", "Can manage documents"),
                    ("view_compliance", "Can view scoped compliance items"),
                    ("view_feedback", "Can view scoped feedback"),
                    (
                        "view_platform_tasks",
                        "Can view sanitized platform task status",
                    ),
                    ("manage_offices", "Can manage scoped offices"),
                    ("view_it_support", "Can view scoped IT support requests"),
                    (
                        "manage_quick_access",
                        "Can manage scoped Quick Access links",
                    ),
                    (
                        "manage_company_quick_access",
                        "Can manage company-wide Quick Access links",
                    ),
                    ("view_reports", "Can view the operational reports catalog"),
                    ("export_reports", "Can export operational reports"),
                ),
            },
        ),
        migrations.CreateModel(
            name="ReportExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_key",
                    models.SlugField(max_length=64, verbose_name="report key"),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="filters"),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("json", "JSON")],
                        default="csv",
                        max_length=8,
                        verbose_name="format",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text=(
                            "Hash of requestor + report + filters + format. "
                            "Duplicate requests within the idempotency window "
                            "reuse the same job."
                        ),
                        max_length=80,
                        verbose_name="idempotency key",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="progress"
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=500, verbose_name="error"),
                ),
                (
                    "scope_level",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="scope level"
                    ),
                ),
                (
                    "calculation_version",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="calculation version"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        storage=apps.user.storage.private_storage,
                        upload_to=apps.web.models._report_export_upload_to,
                        verbose_name="file",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="content type"
                    ),
                ),
                (
                    "byte_size",
                    models.PositiveIntegerField(default=0, verbose_name="byte size"),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="requested at",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "data_as_of",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data as of"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="expires at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_export_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requested by",
                    ),
                ),
            ],
            options={
                "verbose_name": "report export job",
                "verbose_name_plural": "report export jobs",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["requested_by", "report_key", "-requested_at"],
                        name="web_rex_user_report",
                    )
                ],
            },
        ),
        migrations.RunPython(grant_permissions, revoke_permissions),
    ]
