# Generated by Django 6.0.8 on 2026-08-28 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_reporting_export_framework"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationspermission",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("view_users", "Can view scoped users"),
                    ("view_new_agents", "Can view scoped new agents"),
                    (
                        "manage_new_agent_onboarding",
                        "Can manage scoped new-agent onboarding",
                    ),
                    ("add_users", "Can add users"),
                    ("assign_user_roles", "Can assign user roles"),
                    ("view_agent_contracts", "Can view scoped agent contracts"),
                    ("view_transactions", "Can view scoped transactions"),
                    ("view_inventory", "Can view scoped inventory"),
                    ("view_reservations", "Can view scoped reservations"),
                    ("manage_announcements", "Can manage announcements"),
                    (
                        "publish_announcements",
                        "Can publish, schedule, and archive announcements",
                    ),
                    ("pin_announcements", "Can pin announcements"),
                    ("manage_training", "Can manage training"),
                    ("manage_documents", "Can manage documents"),
                    ("view_compliance", "Can view scoped compliance items"),
                    ("view_feedback", "Can view scoped feedback"),
                    ("view_platform_tasks", "Can view sanitized platform task status"),
                    ("view_operational_tasks", "Can view scoped operational tasks"),
                    (
                        "manage_operational_tasks",
                        "Can create and transition operational tasks",
                    ),
                    ("assign_operational_tasks", "Can assign operational tasks"),
                    ("comment_operational_tasks", "Can comment on operational tasks"),
                    ("manage_offices", "Can manage scoped offices"),
                    ("view_it_support", "Can view scoped IT support requests"),
                    ("manage_quick_access", "Can manage scoped Quick Access links"),
                    (
                        "manage_company_quick_access",
                        "Can manage company-wide Quick Access links",
                    ),
                    ("view_reports", "Can view the operational reports catalog"),
                    ("export_reports", "Can export operational reports"),
                ),
            },
        ),
    ]
