const URLS = {
    'logout': () => `/logout`,
    'dashboard': () => `/dashboard`,
    'login': () => `/login`,
    'home': () => `/`,
    'microsoft_callback': () => `/accounts/microsoft/login/callback/`,
    'microsoft_login': () => `/accounts/microsoft/login/`,
    'socialaccount_connections': () => `/accounts/3rdparty/`,
    'socialaccount_signup': () => `/accounts/3rdparty/signup/`,
    'socialaccount_login_error': () => `/accounts/3rdparty/login/error/`,
    'socialaccount_login_cancelled': () => `/accounts/3rdparty/login/cancelled/`,
    'account_reset_password_done': () => `/accounts/password/reset/done/`,
    'account_reset_password_from_key': (uidb36: string, key: string) => `/accounts/password/reset/key/${uidb36}-${key}/`,
    'account_reset_password_from_key_done': () => `/accounts/password/reset/key/done/`,
    'account_confirm_email': (key: string) => `/accounts/confirm-email/${key}/`,
    'account_confirm_login_code': () => `/accounts/login/code/confirm/`,
    'account_reset_password': () => `/accounts/password/reset/`,
    'account_set_password': () => `/accounts/password/set/`,
    'account_change_password': () => `/accounts/password/change/`,
    'account_email_verification_sent': () => `/accounts/confirm-email/`,
    'account_email': () => `/accounts/email/`,
    'account_reauthenticate': () => `/accounts/reauthenticate/`,
    'account_signup': () => `/accounts/signup/`,
    'account_inactive': () => `/accounts/inactive/`,
    'account_logout': () => `/accounts/logout/`,
    'account_login': () => `/accounts/login/`,
};
export default URLS;
