# Generated by Django 6.0.8 on 2026-08-22 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0024_officeresource_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Stable machine key used in URLs, audits, and presentation maps. Set once at creation and never changed.",
                        max_length=40,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("label", models.CharField(max_length=80, verbose_name="label")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive categories cannot be assigned to new announcements but remain readable on existing ones.",
                        verbose_name="active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="display order"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Seeded by the catalog. Can be relabelled, never deleted.",
                        verbose_name="system category",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "announcement category",
                "verbose_name_plural": "announcement categories",
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, verbose_name="slug")),
                ("title", models.CharField(max_length=180, verbose_name="title")),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=280, verbose_name="summary"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="body")),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("urgent", "Urgent"),
                            ("important", "Important"),
                            ("normal", "Normal"),
                        ],
                        help_text="Required to publish. Affects ordering and notification policy only — never who can see the announcement.",
                        max_length=16,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Empty means visible as soon as it is published.",
                        null=True,
                        verbose_name="publishes at",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Empty means it never leaves the feed.",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="published at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "owner_office",
                    models.ForeignKey(
                        help_text="The audience. Head office publishes brokerage-wide, a region to its region, a branch to itself.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="user.office",
                        verbose_name="owning office",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required to publish. PROTECT keeps referenced rows alive.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="announcements.announcementcategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "announcement",
                "verbose_name_plural": "announcements",
                "ordering": ["-published_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["owner_office", "status"],
                        name="announcement_scope_status",
                    ),
                    models.Index(
                        fields=["status", "priority", "-published_at"],
                        name="announcement_feed_order",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_office", "slug"),
                        name="announcement_unique_slug_per_office",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "published"), _negated=True),
                            models.Q(
                                ("category__isnull", False),
                                models.Q(("priority", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="announcement_published_requires_taxonomy",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_at__isnull", True),
                            ("publish_at__isnull", True),
                            ("expires_at__gt", models.F("publish_at")),
                            _connector="OR",
                        ),
                        name="announcement_window_ordered",
                    ),
                ],
            },
        ),
    ]
