# Generated by Django 6.0.8 on 2026-08-22 02:14

import apps.user.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0002_seed_categories"),
        ("user", "0024_officeresource_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Stored in protected storage and only reachable through the download view, which re-evaluates the audience on every request.",
                max_length=255,
                storage=apps.user.storage.private_storage,
                upload_to="announcements/%Y/%m/",
                verbose_name="attachment",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="attachment_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="original file name"
            ),
        ),
        migrations.CreateModel(
            name="AnnouncementAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("company", "Everyone at the brokerage"),
                            ("role", "Everyone holding a role"),
                            ("region", "A region and the offices under it"),
                            ("office", "One office only"),
                            ("user", "One named person"),
                        ],
                        max_length=16,
                        verbose_name="kind",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Stable role catalog code. Only for role selectors.",
                        max_length=64,
                        verbose_name="role code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiences",
                        to="announcements.announcement",
                        verbose_name="announcement",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        help_text="The region or office targeted. A region selector reaches every office beneath it; an office selector reaches that office alone.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcement_audiences",
                        to="user.office",
                        verbose_name="office",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_audiences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "announcement audience",
                "verbose_name_plural": "announcement audiences",
                "indexes": [
                    models.Index(
                        fields=["kind", "office"], name="announcement_aud_office"
                    ),
                    models.Index(fields=["kind", "role"], name="announcement_aud_role"),
                    models.Index(fields=["kind", "user"], name="announcement_aud_user"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "company"),
                                ("office__isnull", True),
                                ("role", ""),
                                ("user__isnull", True),
                            ),
                            models.Q(
                                ("kind", "role"),
                                ("office__isnull", True),
                                ("user__isnull", True),
                                models.Q(("role", ""), _negated=True),
                            ),
                            models.Q(
                                ("kind__in", ["region", "office"]),
                                ("office__isnull", False),
                                ("role", ""),
                                ("user__isnull", True),
                            ),
                            models.Q(
                                ("kind", "user"),
                                ("office__isnull", True),
                                ("role", ""),
                                ("user__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="announcement_audience_one_target_per_kind",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "company")),
                        fields=("announcement",),
                        name="announcement_audience_one_company_row",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "role")),
                        fields=("announcement", "role"),
                        name="announcement_audience_unique_role",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("office__isnull", False)),
                        fields=("announcement", "kind", "office"),
                        name="announcement_audience_unique_office",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "user")),
                        fields=("announcement", "user"),
                        name="announcement_audience_unique_user",
                    ),
                ],
            },
        ),
    ]
