# Generated by Django 6.0.8 on 2026-08-22 10:59

import apps.announcements.models
import apps.user.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_backfill_owner_office_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='attachment_name',
        ),
        migrations.CreateModel(
            name='AnnouncementMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('hero', 'Hero image'), ('attachment', 'Attachment')], max_length=16, verbose_name='role')),
                ('display_name', models.CharField(help_text="The uploader's filename, shown to readers. Never a path.", max_length=180, verbose_name='display name')),
                ('file', models.FileField(max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.announcements.models._media_upload_to, verbose_name='file')),
                ('media_type', models.CharField(max_length=120, verbose_name='media type')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='size in bytes')),
                ('checksum', models.CharField(help_text='SHA-256 of the stored bytes, verified before processing.', max_length=64, verbose_name='checksum')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('variants', models.JSONField(blank=True, default=dict, help_text='Generated responsive derivatives, keyed by label. Served through the same audience check as the original.', verbose_name='variants')),
                ('processing_state', models.CharField(choices=[('pending', 'Processing'), ('ready', 'Ready'), ('quarantined', 'Quarantined'), ('failed', 'Processing failed')], default='pending', max_length=16, verbose_name='processing state')),
                ('processing_note', models.CharField(blank=True, help_text='Why a file was quarantined or failed. Shown to admins only.', max_length=255, verbose_name='processing note')),
                ('is_active', models.BooleanField(default=True, help_text='Cleared instead of deleting once an announcement has been published, so retained history keeps its files.', verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='announcements.announcement', verbose_name='announcement')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_media_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'announcement media',
                'verbose_name_plural': 'announcement media',
                'ordering': ['role', 'sort_order', 'pk'],
                'indexes': [models.Index(fields=['announcement', 'role', 'sort_order'], name='announcement_media_order'), models.Index(fields=['processing_state'], name='announcement_media_state')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'hero')), fields=('announcement',), name='announcement_one_active_hero'), models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='announcement_media_has_bytes'), models.CheckConstraint(condition=models.Q(models.Q(('role', 'hero'), _negated=True), models.Q(('height__isnull', False), ('width__isnull', False)), _connector='OR'), name='announcement_hero_has_dimensions')],
            },
        ),
    ]
