# Generated by Django 6.0.8 on 2026-08-22 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0005_remove_announcement_attachment_and_more"),
        ("user", "0024_officeresource_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="archived at"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="cta_label",
            field=models.CharField(
                blank=True,
                help_text="Button text. Required whenever a link is given.",
                max_length=60,
                verbose_name="call to action label",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="cta_url",
            field=models.URLField(
                blank=True,
                help_text="https destination opened by the button.",
                max_length=500,
                verbose_name="call to action link",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Pinned announcements sort above everything else in the feed and the dashboard band. Pinning never widens the audience.",
                verbose_name="pinned",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="pinned_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="pinned at"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Whoever last wrote to the row, shown beside the timestamp.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="last edited by",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["status", "is_pinned", "-published_at"],
                name="announcement_pinned_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cta_label", ""), ("cta_url", "")),
                    models.Q(
                        models.Q(("cta_label", ""), _negated=True),
                        models.Q(("cta_url", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="announcement_cta_is_complete",
            ),
        ),
    ]
