# Generated by Django 6.0.8 on 2026-08-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "announcements",
            "0006_announcement_archived_at_announcement_cta_label_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="cta_url",
            field=models.CharField(
                blank=True,
                help_text="https:// or mailto: address, or a hub path starting with /. Validated against the same allowlist body links use.",
                max_length=500,
                verbose_name="call to action link",
            ),
        ),
    ]
