# Generated by Django 6.0.8 on 2026-09-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_announcement_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='ai_assisted_body',
            field=models.BooleanField(default=False, help_text='Author accepted an AI suggestion into the body field.', verbose_name='AI-assisted body'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='ai_assisted_summary',
            field=models.BooleanField(default=False, help_text='Author accepted an AI suggestion into the summary field.', verbose_name='AI-assisted summary'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='source_publisher',
            field=models.CharField(blank=True, help_text='Site or publisher name shown as attribution when set.', max_length=120, verbose_name='source publisher'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='source_retrieved_at',
            field=models.DateTimeField(blank=True, help_text='When article metadata was last fetched for authoring.', null=True, verbose_name='source retrieved at'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='source_url',
            field=models.CharField(blank=True, help_text='Optional public HTTPS article this announcement attributes. Separate from the call-to-action button.', max_length=500, verbose_name='source article URL'),
        ),
    ]
