# Generated by Django 6.0.8 on 2026-09-01 05:13

import apps.training.models
import apps.user.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0028_inventory_role_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=80, verbose_name='label')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='display order')),
                ('is_system', models.BooleanField(default=False, editable=False, verbose_name='system category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'training category',
                'verbose_name_plural': 'training categories',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, verbose_name='slug')),
                ('title', models.CharField(max_length=180, verbose_name='title')),
                ('summary', models.CharField(blank=True, max_length=280, verbose_name='summary')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('guide', 'Guide'), ('video', 'Video'), ('checklist', 'Checklist'), ('course', 'Course'), ('quiz', 'Quiz'), ('live_session', 'Live session'), ('recording', 'Recording'), ('tool_onboarding', 'Tool onboarding')], max_length=32, verbose_name='content type')),
                ('is_required', models.BooleanField(default=False, help_text='Required training for the matched audience.', verbose_name='required')),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='estimated minutes')),
                ('tool_code', models.CharField(blank=True, help_text='For tool onboarding content. Matches onboarding tool codes.', max_length=32, verbose_name='tool code')),
                ('external_url', models.CharField(blank=True, help_text='Optional https:// link opened in a new tab.', max_length=500, verbose_name='external link')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16, verbose_name='status')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='publishes at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='published at')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='archived at')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to='training.trainingcategory', verbose_name='category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_content_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_content', to='user.office', verbose_name='owning office')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_content_edited', to=settings.AUTH_USER_MODEL, verbose_name='last edited by')),
            ],
            options={
                'verbose_name': 'training content',
                'verbose_name_plural': 'training content',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('company', 'Everyone at the brokerage'), ('role', 'Everyone holding a role'), ('region', 'A region and the offices under it'), ('office', 'One office only'), ('user', 'One named person')], max_length=16, verbose_name='kind')),
                ('role', models.CharField(blank=True, max_length=64, verbose_name='role code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_audiences', to='user.office', verbose_name='office')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_audiences', to=settings.AUTH_USER_MODEL, verbose_name='person')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='training.trainingcontent', verbose_name='content')),
            ],
            options={
                'verbose_name': 'training audience',
                'verbose_name_plural': 'training audiences',
            },
        ),
        migrations.CreateModel(
            name='TrainingEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='embed URL')),
                ('provider', models.CharField(max_length=32, verbose_name='provider')),
                ('host', models.CharField(max_length=120, verbose_name='host')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embed', to='training.trainingcontent', verbose_name='content')),
            ],
            options={
                'verbose_name': 'training embed',
                'verbose_name_plural': 'training embeds',
            },
        ),
        migrations.CreateModel(
            name='TrainingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary media'), ('attachment', 'Attachment')], max_length=16, verbose_name='role')),
                ('display_name', models.CharField(max_length=180, verbose_name='display name')),
                ('file', models.FileField(max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.training.models._media_upload_to, verbose_name='file')),
                ('media_type', models.CharField(max_length=120, verbose_name='media type')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='size in bytes')),
                ('checksum', models.CharField(max_length=64, verbose_name='checksum')),
                ('processing_state', models.CharField(choices=[('pending', 'Processing'), ('ready', 'Ready'), ('quarantined', 'Quarantined'), ('failed', 'Processing failed')], default='pending', max_length=16, verbose_name='processing state')),
                ('processing_note', models.CharField(blank=True, max_length=255, verbose_name='processing note')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='training.trainingcontent', verbose_name='content')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_media_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'training media',
                'verbose_name_plural': 'training media',
                'ordering': ['role', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_courses', to='training.trainingcontent', verbose_name='module')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.trainingcontent', verbose_name='course')),
            ],
            options={
                'verbose_name': 'training module',
                'verbose_name_plural': 'training modules',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=16, verbose_name='status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='training.trainingcontent', verbose_name='content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'training progress',
                'verbose_name_plural': 'training progress',
            },
        ),
        migrations.CreateModel(
            name='TrainingTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', models.JSONField(default=list, help_text='List of {startMs, endMs, text} objects.', verbose_name='segments')),
                ('search_text', models.TextField(blank=True, editable=False, verbose_name='search text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='training.trainingcontent', verbose_name='content')),
            ],
            options={
                'verbose_name': 'training transcription',
                'verbose_name_plural': 'training transcriptions',
            },
        ),
        migrations.AddIndex(
            model_name='trainingcontent',
            index=models.Index(fields=['status', 'is_required', 'display_order'], name='training_library_order'),
        ),
        migrations.AddIndex(
            model_name='trainingcontent',
            index=models.Index(fields=['status', 'content_type'], name='training_status_type'),
        ),
        migrations.AddConstraint(
            model_name='trainingcontent',
            constraint=models.UniqueConstraint(fields=('owner_office', 'slug'), name='training_content_unique_slug_per_office'),
        ),
        migrations.AddConstraint(
            model_name='trainingcontent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('category__isnull', False), _connector='OR'), name='training_published_requires_category'),
        ),
        migrations.AddConstraint(
            model_name='trainingcontent',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('publish_at__isnull', True), ('expires_at__gt', models.F('publish_at')), _connector='OR'), name='training_window_ordered'),
        ),
        migrations.AddIndex(
            model_name='trainingaudience',
            index=models.Index(fields=['kind', 'office'], name='training_aud_office'),
        ),
        migrations.AddIndex(
            model_name='trainingaudience',
            index=models.Index(fields=['kind', 'role'], name='training_aud_role'),
        ),
        migrations.AddIndex(
            model_name='trainingaudience',
            index=models.Index(fields=['kind', 'user'], name='training_aud_user'),
        ),
        migrations.AddConstraint(
            model_name='trainingaudience',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'company'), ('office__isnull', True), ('role', ''), ('user__isnull', True)), models.Q(('kind', 'role'), ('office__isnull', True), ('user__isnull', True), models.Q(('role', ''), _negated=True)), models.Q(('kind__in', ['region', 'office']), ('office__isnull', False), ('role', ''), ('user__isnull', True)), models.Q(('kind', 'user'), ('office__isnull', True), ('role', ''), ('user__isnull', False)), _connector='OR'), name='training_audience_one_target_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='trainingaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'company')), fields=('content',), name='training_audience_one_company_row'),
        ),
        migrations.AddConstraint(
            model_name='trainingaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'role')), fields=('content', 'role'), name='training_audience_unique_role'),
        ),
        migrations.AddConstraint(
            model_name='trainingaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('office__isnull', False)), fields=('content', 'kind', 'office'), name='training_audience_unique_office'),
        ),
        migrations.AddConstraint(
            model_name='trainingaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'user')), fields=('content', 'user'), name='training_audience_unique_user'),
        ),
        migrations.AddConstraint(
            model_name='trainingmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'primary')), fields=('content',), name='training_one_active_primary'),
        ),
        migrations.AddConstraint(
            model_name='trainingmedia',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='training_media_has_bytes'),
        ),
        migrations.AddConstraint(
            model_name='trainingmodule',
            constraint=models.UniqueConstraint(fields=('course', 'child'), name='training_module_unique_child'),
        ),
        migrations.AddIndex(
            model_name='trainingprogress',
            index=models.Index(fields=['user', 'status'], name='training_progress_user'),
        ),
        migrations.AddConstraint(
            model_name='trainingprogress',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='training_progress_unique_user_content'),
        ),
    ]
