# Generated by Django 6.0.8 on 2026-09-02 08:54

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_seed_categories'),
        ('user', '0028_inventory_role_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcontent',
            name='version_family',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Shared across successive versions of the same training item.', verbose_name='version family'),
        ),
        migrations.AddField(
            model_name='trainingcontent',
            name='version_number',
            field=models.PositiveIntegerField(default=1, verbose_name='version number'),
        ),
        migrations.AddIndex(
            model_name='trainingcontent',
            index=models.Index(fields=['version_family', 'version_number'], name='training_version_family'),
        ),
        migrations.AddConstraint(
            model_name='trainingcontent',
            constraint=models.UniqueConstraint(fields=('version_family', 'version_number'), name='training_content_unique_version'),
        ),
    ]
