# Generated by Django 6.0.8 on 2026-09-02 14:36

import apps.training.models
import apps.user.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_content_versioning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='pending', max_length=16, verbose_name='status')),
                ('file', models.FileField(blank=True, max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.training.models._certificate_upload_to, verbose_name='file')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'training certificate',
                'verbose_name_plural': 'training certificates',
            },
        ),
        migrations.CreateModel(
            name='TrainingLiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='starts at')),
                ('timezone', models.CharField(default='America/New_York', help_text='IANA timezone for display.', max_length=64, verbose_name='timezone')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='duration minutes')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited capacity.', null=True, verbose_name='capacity')),
                ('meeting_url', models.CharField(blank=True, max_length=500, verbose_name='meeting URL')),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True, verbose_name='registration opens at')),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True, verbose_name='registration closes at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'training live session',
                'verbose_name_plural': 'training live sessions',
            },
        ),
        migrations.CreateModel(
            name='TrainingQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_threshold_percent', models.PositiveSmallIntegerField(default=80, verbose_name='pass threshold percent')),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, help_text='Leave blank for unlimited attempts.', null=True, verbose_name='max attempts')),
                ('feedback_policy', models.CharField(choices=[('none', 'No feedback'), ('score_only', 'Score only'), ('review', 'Score and review')], default='score_only', max_length=16, verbose_name='feedback policy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'training quiz',
                'verbose_name_plural': 'training quizzes',
            },
        ),
        migrations.CreateModel(
            name='TrainingQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(verbose_name='attempt number')),
                ('answers', models.JSONField(default=dict, verbose_name='answers')),
                ('score_percent', models.PositiveSmallIntegerField(verbose_name='score percent')),
                ('passed', models.BooleanField(default=False, verbose_name='passed')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('content_version_number', models.PositiveIntegerField(verbose_name='content version number')),
            ],
            options={
                'verbose_name': 'training quiz attempt',
                'verbose_name_plural': 'training quiz attempts',
            },
        ),
        migrations.CreateModel(
            name='TrainingQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500, verbose_name='prompt')),
                ('choices', models.JSONField(default=list, help_text='List of {id, label} objects.', verbose_name='choices')),
                ('correct_choice_ids', models.JSONField(default=list, help_text='Server-only. Never serialize to learners.', verbose_name='correct choice ids')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'training quiz question',
                'verbose_name_plural': 'training quiz questions',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No show')], default='registered', max_length=16, verbose_name='status')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='registered at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='attended at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'training session registration',
                'verbose_name_plural': 'training session registrations',
            },
        ),
        migrations.AddField(
            model_name='trainingcontent',
            name='version_completion_policy',
            field=models.CharField(choices=[('current_version', 'Current live version'), ('any_version', 'Any completed version')], default='any_version', help_text='Whether required-training satisfaction needs the live version (current_version) or any completed version (any_version).', max_length=32, verbose_name='version completion policy'),
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='content_version_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='content version number'),
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='evidence',
            field=models.JSONField(blank=True, default=dict, verbose_name='evidence'),
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='is_required_at_completion',
            field=models.BooleanField(blank=True, null=True, verbose_name='required at completion'),
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='progress percent'),
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='source',
            field=models.CharField(blank=True, choices=[('learner', 'Learner'), ('quiz', 'Quiz'), ('session', 'Live session'), ('course_rollup', 'Course rollup'), ('admin_correction', 'Admin correction'), ('system', 'System')], default='system', max_length=32, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='started at'),
        ),
        migrations.AddIndex(
            model_name='trainingprogress',
            index=models.Index(fields=['content', 'status'], name='training_progress_content'),
        ),
        migrations.AddConstraint(
            model_name='trainingprogress',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__isnull', True), models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), _connector='OR'), name='training_progress_percent_range'),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_certificates_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='training.trainingcontent', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_certificates', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='traininglivesession',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_session', to='training.trainingcontent', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='trainingquiz',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='training.trainingcontent', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='trainingquizattempt',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='training.trainingcontent', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='trainingquizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='trainingquizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.trainingquiz', verbose_name='quiz'),
        ),
        migrations.AddField(
            model_name='trainingsessionregistration',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_registrations', to='training.trainingcontent', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='trainingsessionregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_session_registrations', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddConstraint(
            model_name='trainingcertificate',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='training_certificate_unique_user'),
        ),
        migrations.AddConstraint(
            model_name='trainingquiz',
            constraint=models.CheckConstraint(condition=models.Q(('pass_threshold_percent__gte', 0), ('pass_threshold_percent__lte', 100)), name='training_quiz_threshold_range'),
        ),
        migrations.AddIndex(
            model_name='trainingquizattempt',
            index=models.Index(fields=['user', 'content'], name='training_quiz_attempt_user'),
        ),
        migrations.AddConstraint(
            model_name='trainingquizattempt',
            constraint=models.UniqueConstraint(fields=('user', 'content', 'attempt_number'), name='training_quiz_attempt_unique'),
        ),
        migrations.AddConstraint(
            model_name='trainingquizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('score_percent__gte', 0), ('score_percent__lte', 100)), name='training_quiz_score_range'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionregistration',
            index=models.Index(fields=['content', 'status'], name='training_session_reg_status'),
        ),
        migrations.AddConstraint(
            model_name='trainingsessionregistration',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='training_session_reg_unique_user'),
        ),
    ]
