# Generated by Django 6.0.8 on 2026-08-28 01:59

import apps.operational_tasks.models
import apps.user.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0025_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('reference', models.CharField(blank=True, max_length=16, unique=True, verbose_name='reference')),
                ('category', models.CharField(choices=[('onboarding_issue', 'Onboarding issue'), ('permission_request', 'Permission request'), ('tool_setup', 'Tool setup'), ('content_update', 'Content update'), ('office_setup', 'Office setup'), ('integration_incident', 'Integration incident'), ('bug', 'Bug'), ('support_follow_up', 'Support follow-up')], max_length=40, verbose_name='category')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('source', models.CharField(choices=[('manual', 'Created directly'), ('feedback', 'Converted from feedback'), ('automation', 'Raised by automation')], default='manual', max_length=20, verbose_name='source')),
                ('source_reference', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='source reference')),
                ('team', models.CharField(blank=True, max_length=60, verbose_name='team')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Normal'), (4, 'Low')], default=3, verbose_name='priority')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('waiting', 'Waiting on requester'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20, verbose_name='status')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='due at')),
                ('related_object_type', models.CharField(blank=True, max_length=60, verbose_name='related object type')),
                ('related_object_id', models.CharField(blank=True, max_length=64, verbose_name='related object id')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operational_tasks', to=settings.AUTH_USER_MODEL, verbose_name='assignee')),
                ('office', models.ForeignKey(help_text='The node that owns this work. Scope is read from it.', on_delete=django.db.models.deletion.PROTECT, related_name='operational_tasks', to='user.office', verbose_name='owning office')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_operational_tasks', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
                ('visible_to', models.ManyToManyField(blank=True, help_text='People who may read this task regardless of office scope. Grants read access to this record only and widens nothing else.', related_name='visible_operational_tasks', to=settings.AUTH_USER_MODEL, verbose_name='explicitly visible to')),
            ],
            options={
                'verbose_name': 'operational task',
                'verbose_name_plural': 'operational tasks',
                'ordering': ['-created_at', '-pk'],
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('file', models.FileField(storage=apps.user.storage.private_storage, upload_to=apps.operational_tasks.models.attachment_upload_to, verbose_name='file')),
                ('display_name', models.CharField(max_length=200, verbose_name='display name')),
                ('media_type', models.CharField(blank=True, max_length=100, verbose_name='media type')),
                ('byte_size', models.PositiveBigIntegerField(default=0, verbose_name='size in bytes')),
                ('internal', models.BooleanField(default=False, verbose_name='internal only')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operational_tasks.operationaltask', verbose_name='task')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_task_attachments', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'task attachment',
                'verbose_name_plural': 'task attachments',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('body', models.TextField(verbose_name='body')),
                ('internal', models.BooleanField(default=False, help_text='Staff-only. Never shown to the reporter or a shared reader.', verbose_name='internal only')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_task_comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operational_tasks.operationaltask', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task comment',
                'verbose_name_plural': 'task comments',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='operationaltask',
            index=models.Index(fields=['office', 'status'], name='optask_office_status_idx'),
        ),
        migrations.AddIndex(
            model_name='operationaltask',
            index=models.Index(fields=['assignee', 'status'], name='optask_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='operationaltask',
            index=models.Index(fields=['status', 'due_at'], name='optask_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='operationaltask',
            index=models.Index(fields=['category'], name='optask_category_idx'),
        ),
        migrations.AddIndex(
            model_name='operationaltask',
            index=models.Index(fields=['source', 'source_reference'], name='optask_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationaltask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', False), ('status__in', ['cancelled', 'closed'])), models.Q(models.Q(('status__in', ['cancelled', 'closed']), _negated=True), ('closed_at__isnull', True)), _connector='OR'), name='operational_task_closed_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='operationaltask',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='operational_task_requires_title'),
        ),
        migrations.AddConstraint(
            model_name='operationaltask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('related_object_type', ''), ('related_object_id', '')), models.Q(models.Q(('related_object_type', ''), _negated=True), models.Q(('related_object_id', ''), _negated=True)), _connector='OR'), name='operational_task_related_pointer_is_complete'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task', 'internal'], name='optask_att_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'internal', 'created_at'], name='optask_cmt_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskcomment',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='operational_task_comment_requires_body'),
        ),
    ]
