# Generated by Django 6.0.8 on 2026-08-28 22:48

import apps.operational_tasks.models
import apps.user.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.operational_tasks.models.attachment_upload_to, verbose_name='file'),
        ),
    ]
