# Generated by Django 6.0.8 on 2026-08-17 19:15

from django.db import migrations, models


# Users who already existed before the onboarding flow was introduced are
# considered complete — only new signups (profile_completed defaults to
# False) are sent through the /onboarding flow.
def mark_existing_users_complete(apps, schema_editor):
    User = apps.get_model("user", "User")
    User.objects.filter(profile_completed=False).update(profile_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_default_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Whether the user finished the post-signup details flow (onboarding). New SSO users are redirected to /onboarding until this is true.', verbose_name='profile completed'),
        ),
        migrations.RunPython(mark_existing_users_complete, migrations.RunPython.noop),
    ]
