# Generated by Django 6.0.8 on 2026-08-18 18:04

import django.db.models.deletion
from django.db import migrations, models


def seed_org_tree(apps, schema_editor):
    from apps.user.office_seed import seed_offices

    report = seed_offices(apps.get_model("user", "Office"))
    if report.conflicting:
        raise RuntimeError(f"Office seed conflicts: {report.conflicting}")


def unseed_org_tree(apps, schema_editor):
    User = apps.get_model("user", "User")
    Office = apps.get_model("user", "Office")
    User.objects.filter(office__isnull=False).update(office=None)
    # Parent FKs use PROTECT, so delete leaves first.
    Office.objects.filter(kind="branch").delete()
    Office.objects.filter(kind="regional_office").delete()
    Office.objects.filter(kind="region").delete()
    Office.objects.filter(kind="head_office").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_phone_number_user_profile_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="city"),
        ),
        migrations.AddField(
            model_name="user",
            name="mls_number",
            field=models.CharField(
                blank=True,
                help_text="Optional. Can be added later from the profile page.",
                max_length=32,
                verbose_name="MLS number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nrds_number",
            field=models.CharField(
                blank=True,
                help_text="Optional 8- or 9-digit NRDS ID. Can be added later.",
                max_length=9,
                verbose_name="NRDS number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DC", "District of Columbia"),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                ],
                max_length=2,
                verbose_name="state",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="street_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="street address"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="ZIP code"),
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="slug"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("head_office", "Head office"),
                            ("region", "Region"),
                            ("regional_office", "Regional office"),
                            ("branch", "Branch"),
                        ],
                        max_length=32,
                        verbose_name="kind",
                    ),
                ),
                (
                    "is_assignable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether a user can pick this office as their work location.",
                        verbose_name="assignable",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="sort order"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="user.office",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "office",
                "verbose_name_plural": "offices",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="user.office",
                verbose_name="office",
            ),
        ),
        migrations.RunPython(seed_org_tree, unseed_org_tree),
    ]
