# Generated by Django 6.0.8 on 2026-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_headshot_and_completion_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="headshot",
            field=models.ImageField(
                blank=True,
                help_text="Profile photo. Must be JPEG/PNG, ≤5 MB, at least 200×200 px.",
                null=True,
                upload_to="apps.user.headshot.headshot_upload_path",
                verbose_name="headshot",
            ),
        ),
    ]
