# Generated by Django 6.0.8 on 2026-08-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user",
            "0010_remove_userroleassignment_user_role_assignment_company_scope_empty_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="A short introduction shown alongside your name in the hub.",
                max_length=1500,
                verbose_name="professional bio",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="user",
            name="languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Language codes from 32 supported options.",
                verbose_name="languages",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="license_expires_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="license expires on"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="Real estate license number, as printed on the license.",
                max_length=32,
                verbose_name="license number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="license_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DC", "District of Columbia"),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                ],
                max_length=2,
                verbose_name="license state",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone call"),
                    ("text", "Text message"),
                ],
                max_length=16,
                verbose_name="preferred contact method",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="What colleagues and clients should call you, if not your legal first name.",
                max_length=150,
                verbose_name="preferred name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="website_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="website"),
        ),
        migrations.AddField(
            model_name="user",
            name="x_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="X"),
        ),
    ]
