# Generated by Django 6.0.8 on 2026-08-20 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0012_headshot_upload_path_callable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    (
                        "view_user_administration",
                        "Can view administrative profile fields",
                    ),
                    (
                        "change_user_administration",
                        "Can change administrative profile fields",
                    ),
                ),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="administration_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="administration updated at"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="administration_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="administered_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="administration updated by",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="agent_identifier",
            field=models.CharField(
                blank=True,
                help_text="Internal identifier used by back-office systems.",
                max_length=32,
                verbose_name="agent ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="agent_status",
            field=models.CharField(
                choices=[
                    ("prospective", "Prospective"),
                    ("active", "Active"),
                    ("on_leave", "On leave"),
                    ("suspended", "Suspended"),
                    ("departed", "Departed"),
                ],
                default="active",
                help_text="Where this person stands with the brokerage.",
                max_length=16,
                verbose_name="agent status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                help_text="Administrative notes about this person. Visible only to administrators with the change permission; never shown to the person themselves and never written into audit values.",
                verbose_name="operational notes",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="license_verification_note",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="verification note"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="license_verification_state",
            field=models.CharField(
                choices=[
                    ("unverified", "Not verified"),
                    ("pending", "Verification pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="unverified",
                help_text="Set by the broker after checking the state license record.",
                max_length=16,
                verbose_name="license verification",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="license_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="license verified at"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="license_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verified_licenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="license verified by",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="The date this person joined the brokerage.",
                null=True,
                verbose_name="start date",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("agent_identifier", ""), _negated=True),
                fields=("agent_identifier",),
                name="user_agent_identifier_unique_when_set",
            ),
        ),
    ]
