# Generated by Django 6.0.8 on 2026-08-20 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_agent_administration_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboardingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_onboarding_cases', to=settings.AUTH_USER_MODEL, verbose_name='onboarding owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_onboarding_cases', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_case', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user onboarding case',
                'verbose_name_plural': 'user onboarding cases',
                'ordering': ['user__first_name', 'user__last_name', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingToolSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('lofty', 'Lofty'), ('skyslope', 'SkySlope'), ('microsoft365', 'Microsoft 365'), ('dotloop', 'Dotloop')], max_length=32, verbose_name='tool')),
                ('state', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('ready', 'Ready'), ('blocked', 'Blocked'), ('not_required', 'Not required')], default='not_started', max_length=16, verbose_name='state')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_onboarding_tools', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_setups', to='user.useronboardingcase', verbose_name='onboarding case')),
            ],
            options={
                'verbose_name': 'onboarding tool setup',
                'verbose_name_plural': 'onboarding tool setups',
                'ordering': ['tool'],
                'constraints': [models.UniqueConstraint(fields=('case', 'tool'), name='user_onboard_tool_unique')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A brief operational instruction; do not include sensitive data.', max_length=200, verbose_name='task')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='due on')),
                ('is_blocking', models.BooleanField(default=False, verbose_name='blocks activation')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16, verbose_name='status')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_onboarding_tasks', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_onboarding_tasks', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.useronboardingcase', verbose_name='onboarding case')),
            ],
            options={
                'verbose_name': 'onboarding task',
                'verbose_name_plural': 'onboarding tasks',
                'ordering': ['status', 'due_on', 'created_at'],
                'indexes': [models.Index(fields=['case', 'status', 'due_on'], name='user_onboard_task_state')],
            },
        ),
    ]
