# Generated by Django 6.0.8 on 2026-08-20 09:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_primary_memberships(apps, schema_editor):
    User = apps.get_model("user", "User")
    UserOfficeMembership = apps.get_model("user", "UserOfficeMembership")
    today = django.utils.timezone.localdate()
    for user in User.objects.exclude(office_id=None).iterator():
        exists = UserOfficeMembership.objects.filter(
            user_id=user.pk,
            kind="primary",
            status="active",
        ).exists()
        if exists:
            continue
        UserOfficeMembership.objects.create(
            user_id=user.pk,
            office_id=user.office_id,
            kind="primary",
            status="active",
            starts_on=today,
            business_reason=(
                "Backfilled from existing User.office during hierarchy migration."
            ),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_useronboardingcase_onboardingtoolsetup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOfficeMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("primary", "Primary"), ("secondary", "Secondary")],
                        max_length=16,
                        verbose_name="kind",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("starts_on", models.DateField(verbose_name="starts on")),
                (
                    "ends_on",
                    models.DateField(blank=True, null=True, verbose_name="ends on"),
                ),
                (
                    "business_reason",
                    models.TextField(blank=True, verbose_name="business reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "user office membership",
                "verbose_name_plural": "user office memberships",
                "ordering": ["user_id", "kind", "-starts_on", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="office",
            index=models.Index(fields=["parent"], name="user_office_parent"),
        ),
        migrations.AddIndex(
            model_name="office",
            index=models.Index(
                fields=["kind", "is_active"], name="user_office_kind_active"
            ),
        ),
        migrations.AddField(
            model_name="userofficemembership",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="office_membership_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="changed by",
            ),
        ),
        migrations.AddField(
            model_name="userofficemembership",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="user.office",
                verbose_name="office",
            ),
        ),
        migrations.AddField(
            model_name="userofficemembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="office_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="userofficemembership",
            index=models.Index(
                fields=["user", "kind", "status"], name="user_office_memb_user_kind"
            ),
        ),
        migrations.AddIndex(
            model_name="userofficemembership",
            index=models.Index(
                fields=["office", "status"], name="user_office_memb_office_stat"
            ),
        ),
        migrations.AddIndex(
            model_name="userofficemembership",
            index=models.Index(
                fields=["starts_on", "ends_on"], name="user_office_memb_effective"
            ),
        ),
        migrations.AddConstraint(
            model_name="userofficemembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_on__isnull", True),
                    ("ends_on__gte", models.F("starts_on")),
                    _connector="OR",
                ),
                name="user_office_membership_valid_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="userofficemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "primary"), ("status", "active")),
                fields=("user",),
                name="user_office_membership_one_active_primary",
            ),
        ),
        migrations.RunPython(backfill_primary_memberships, migrations.RunPython.noop),
    ]
