# Generated by Django 6.0.8 on 2026-08-21 17:37

from django.db import migrations, models

# Keep BrokerageRole.valid_scope_types aligned with ROLE_DEFINITIONS for the
# three roles that newly accept assigned-record scope.
_ASSIGNED_RECORD_SCOPES = {
    "realtor": ["office", "assigned_record"],
    "transaction_coordinator": ["office", "assigned_record"],
    "regional_transaction_coordinator": ["region", "assigned_record"],
}


def sync_assigned_record_scopes(apps, schema_editor):
    BrokerageRole = apps.get_model("user", "BrokerageRole")
    for code, scopes in _ASSIGNED_RECORD_SCOPES.items():
        BrokerageRole.objects.filter(code=code).update(valid_scope_types=scopes)


def revert_assigned_record_scopes(apps, schema_editor):
    BrokerageRole = apps.get_model("user", "BrokerageRole")
    BrokerageRole.objects.filter(code="realtor").update(valid_scope_types=["office"])
    BrokerageRole.objects.filter(code="transaction_coordinator").update(
        valid_scope_types=["office"]
    )
    BrokerageRole.objects.filter(code="regional_transaction_coordinator").update(
        valid_scope_types=["region"]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0019_grant_account_state_permission"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userroleassignment",
            name="user_role_assignment_company_scope_empty",
        ),
        migrations.AlterField(
            model_name="userroleassignment",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("company", "Company"),
                    ("region", "Region"),
                    ("office", "Office"),
                    ("assigned_record", "Assigned records"),
                ],
                max_length=32,
                verbose_name="scope type",
            ),
        ),
        migrations.AddConstraint(
            model_name="userroleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("scope_office__isnull", True),
                        ("scope_type__in", ["company", "assigned_record"]),
                    ),
                    models.Q(
                        ("scope_type__in", ["company", "assigned_record"]),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="user_role_assignment_org_less_scope_empty",
            ),
        ),
        migrations.RunPython(
            sync_assigned_record_scopes,
            revert_assigned_record_scopes,
        ),
    ]
