# Generated by Django 6.0.8 on 2026-09-06 21:17

import apps.user.timezones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_inventory_role_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='timezone',
            field=models.CharField(default='America/New_York', help_text='IANA timezone used for office schedules and local dates.', max_length=64, validators=[apps.user.timezones.validate_iana_timezone], verbose_name='timezone'),
        ),
    ]
