# Generated by Django 6.0.8 on 2026-09-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0029_office_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='Practice-area codes from 12 supported options.', verbose_name='specialties'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'agent_status'], name='user_directory_visible'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['license_state'], name='user_directory_license'),
        ),
    ]
