# Generated by Django 6.0.8 on 2026-09-11 21:25

import django.db.models.deletion
from django.db import migrations, models


def backfill_onboarding_office_correlations(apps, schema_editor):
    UserOnboardingCase = apps.get_model("user", "UserOnboardingCase")
    cases = UserOnboardingCase.objects.select_related("user").iterator(chunk_size=500)
    for case in cases:
        updates = {}
        if case.office_confirmed_at is not None and case.user.office_id is not None:
            updates["office_confirmed_for_id"] = case.user.office_id
            updates["office_confirmation_version"] = case.user.onboarding_version
        if case.user.office_id is not None:
            updates["office_handoff_office_id"] = case.user.office_id
            updates["office_handoff_onboarding_version"] = case.user.onboarding_version
        if updates:
            UserOnboardingCase.objects.filter(pk=case.pk).update(**updates)


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0031_onboarding_journey_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="useronboardingcase",
            name="office_confirmation_version",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Onboarding cycle covered by the current confirmation.",
                null=True,
                verbose_name="office confirmation onboarding version",
            ),
        ),
        migrations.AddField(
            model_name="useronboardingcase",
            name="office_confirmed_for",
            field=models.ForeignKey(
                blank=True,
                help_text="Office identity covered by the current confirmation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="user.office",
                verbose_name="confirmed office",
            ),
        ),
        migrations.AddField(
            model_name="useronboardingcase",
            name="office_handoff_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="user.office",
                verbose_name="office handoff office",
            ),
        ),
        migrations.AddField(
            model_name="useronboardingcase",
            name="office_handoff_onboarding_version",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="office handoff onboarding version"
            ),
        ),
        migrations.RunPython(
            backfill_onboarding_office_correlations,
            migrations.RunPython.noop,
        ),
    ]
