# Generated by Django 6.0.8 on 2026-09-14 05:41

import apps.documents.models
import apps.user.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0032_useronboardingcase_office_confirmation_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=80, verbose_name='label')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='display order')),
                ('is_system', models.BooleanField(default=False, editable=False, verbose_name='system category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'document category',
                'verbose_name_plural': 'document categories',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identity across successive versions.', max_length=80, unique=True, verbose_name='key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_families', to='user.office', verbose_name='owning office')),
            ],
            options={
                'verbose_name': 'document family',
                'verbose_name_plural': 'document families',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('jurisdiction_state_codes', models.JSONField(blank=True, default=list, help_text='Empty means all jurisdictions.', verbose_name='jurisdiction state codes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16, verbose_name='status')),
                ('effective_at', models.DateTimeField(blank=True, null=True, verbose_name='effective at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='version number')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='display order')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.documentcategory', verbose_name='category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.documentfamily', verbose_name='family')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_document_versions', to=settings.AUTH_USER_MODEL, verbose_name='document owner')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions_published', to=settings.AUTH_USER_MODEL, verbose_name='published by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions_edited', to=settings.AUTH_USER_MODEL, verbose_name='last edited by')),
            ],
            options={
                'verbose_name': 'document version',
                'verbose_name_plural': 'document versions',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=180, verbose_name='display name')),
                ('file', models.FileField(max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.documents.models._file_upload_to, verbose_name='file')),
                ('media_type', models.CharField(max_length=120, verbose_name='media type')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='size in bytes')),
                ('checksum', models.CharField(max_length=64, verbose_name='checksum')),
                ('processing_state', models.CharField(choices=[('pending', 'Processing'), ('ready', 'Ready'), ('quarantined', 'Quarantined'), ('failed', 'Processing failed')], default='pending', max_length=16, verbose_name='processing state')),
                ('processing_note', models.CharField(blank=True, max_length=255, verbose_name='processing note')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_files_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.documentversion', verbose_name='document version')),
            ],
            options={
                'verbose_name': 'document file',
                'verbose_name_plural': 'document files',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('company', 'Everyone at the brokerage'), ('role', 'Everyone holding a role'), ('region', 'A region and the offices under it'), ('office', 'One office only'), ('user', 'One named person')], max_length=16, verbose_name='kind')),
                ('role', models.CharField(blank=True, max_length=64, verbose_name='role code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_audiences', to='user.office', verbose_name='office')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_audiences', to=settings.AUTH_USER_MODEL, verbose_name='person')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='documents.documentversion', verbose_name='document version')),
            ],
            options={
                'verbose_name': 'document audience',
                'verbose_name_plural': 'document audiences',
            },
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['status', 'display_order'], name='documents_library_order'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['family', 'version_number'], name='documents_family_version'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('family', 'version_number'), name='documents_unique_family_version'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('category__isnull', False), _connector='OR'), name='documents_published_requires_category'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('effective_at__isnull', True), ('expires_at__gt', models.F('effective_at')), _connector='OR'), name='documents_window_ordered'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['document_version', 'is_active'], name='documents_file_active'),
        ),
        migrations.AddConstraint(
            model_name='documentfile',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='documents_file_has_bytes'),
        ),
        migrations.AddIndex(
            model_name='documentaudience',
            index=models.Index(fields=['kind', 'office'], name='documents_aud_office'),
        ),
        migrations.AddIndex(
            model_name='documentaudience',
            index=models.Index(fields=['kind', 'role'], name='documents_aud_role'),
        ),
        migrations.AddIndex(
            model_name='documentaudience',
            index=models.Index(fields=['kind', 'user'], name='documents_aud_user'),
        ),
        migrations.AddConstraint(
            model_name='documentaudience',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'company'), ('office__isnull', True), ('role', ''), ('user__isnull', True)), models.Q(('kind', 'role'), ('office__isnull', True), ('user__isnull', True), models.Q(('role', ''), _negated=True)), models.Q(('kind__in', ['region', 'office']), ('office__isnull', False), ('role', ''), ('user__isnull', True)), models.Q(('kind', 'user'), ('office__isnull', True), ('role', ''), ('user__isnull', False)), _connector='OR'), name='documents_audience_one_target'),
        ),
        migrations.AddConstraint(
            model_name='documentaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'company')), fields=('document_version',), name='documents_audience_one_company'),
        ),
        migrations.AddConstraint(
            model_name='documentaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'role')), fields=('document_version', 'role'), name='documents_audience_unique_role'),
        ),
        migrations.AddConstraint(
            model_name='documentaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('office__isnull', False)), fields=('document_version', 'kind', 'office'), name='documents_audience_unique_office'),
        ),
        migrations.AddConstraint(
            model_name='documentaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'user')), fields=('document_version', 'user'), name='documents_audience_unique_user'),
        ),
    ]
