# Generated by Django 6.0.8 on 2026-09-11 09:30

import apps.compliance.models
import apps.user.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0030_agent_directory_specialties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=80, verbose_name='label')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='display order')),
                ('is_system', models.BooleanField(default=False, editable=False, verbose_name='system category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'policy category',
                'verbose_name_plural': 'policy categories',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='title')),
                ('summary', models.CharField(blank=True, max_length=280, verbose_name='summary')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('jurisdiction_state_codes', models.JSONField(blank=True, default=list, help_text='Empty means all jurisdictions.', verbose_name='jurisdiction state codes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16, verbose_name='status')),
                ('effective_at', models.DateTimeField(blank=True, null=True, verbose_name='effective at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('content_checksum', models.CharField(blank=True, help_text='Sealed on publish over body and ready document files.', max_length=64, verbose_name='content checksum')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Audience must acknowledge this published version.', verbose_name='mandatory acknowledgement')),
                ('reacknowledge_on_supersede', models.BooleanField(default=True, help_text='When a newer family sibling is published, create a fresh acknowledgement requirement.', verbose_name='require re-acknowledgement on supersede')),
                ('acknowledgement_disclosure', models.TextField(blank=True, help_text='Text the reader must confirm when acknowledging.', verbose_name='acknowledgement disclosure')),
                ('disclosure_version', models.PositiveIntegerField(default=1, help_text='Bumped when acknowledgement disclosure text changes.', verbose_name='disclosure version')),
                ('version_family', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Shared across successive versions of the same policy.', verbose_name='version family')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='version number')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='display order')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='compliance.policycategory', verbose_name='category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_versions', to='user.office', verbose_name='owning office')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_policy_versions', to=settings.AUTH_USER_MODEL, verbose_name='policy owner')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_versions_published', to=settings.AUTH_USER_MODEL, verbose_name='published by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_versions_edited', to=settings.AUTH_USER_MODEL, verbose_name='last edited by')),
            ],
            options={
                'verbose_name': 'policy version',
                'verbose_name_plural': 'policy versions',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PolicyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='due at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='compliance.policyversion', verbose_name='policy version')),
            ],
            options={
                'verbose_name': 'policy requirement',
                'verbose_name_plural': 'policy requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('document', 'Policy document'), ('source', 'Editable source')], max_length=16, verbose_name='role')),
                ('display_name', models.CharField(max_length=180, verbose_name='display name')),
                ('file', models.FileField(max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.compliance.models._file_upload_to, verbose_name='file')),
                ('media_type', models.CharField(max_length=120, verbose_name='media type')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='size in bytes')),
                ('checksum', models.CharField(max_length=64, verbose_name='checksum')),
                ('processing_state', models.CharField(choices=[('pending', 'Processing'), ('ready', 'Ready'), ('quarantined', 'Quarantined'), ('failed', 'Processing failed')], default='pending', max_length=16, verbose_name='processing state')),
                ('processing_note', models.CharField(blank=True, max_length=255, verbose_name='processing note')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_files_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='compliance.policyversion', verbose_name='policy version')),
            ],
            options={
                'verbose_name': 'policy file',
                'verbose_name_plural': 'policy files',
                'ordering': ['role', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('company', 'Everyone at the brokerage'), ('role', 'Everyone holding a role'), ('region', 'A region and the offices under it'), ('office', 'One office only'), ('user', 'One named person')], max_length=16, verbose_name='kind')),
                ('role', models.CharField(blank=True, max_length=64, verbose_name='role code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_audiences', to='user.office', verbose_name='office')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_audiences', to=settings.AUTH_USER_MODEL, verbose_name='person')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='compliance.policyversion', verbose_name='policy version')),
            ],
            options={
                'verbose_name': 'policy audience',
                'verbose_name_plural': 'policy audiences',
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgementWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='reason')),
                ('waived_at', models.DateTimeField(auto_now_add=True, verbose_name='waived at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgement_waivers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('waived_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_acknowledgement_waivers_granted', to=settings.AUTH_USER_MODEL, verbose_name='waived by')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgement_waivers', to='compliance.policyversion', verbose_name='policy version')),
            ],
            options={
                'verbose_name': 'policy acknowledgement waiver',
                'verbose_name_plural': 'policy acknowledgement waivers',
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_checksum', models.CharField(max_length=64, verbose_name='content checksum')),
                ('disclosure_version', models.PositiveIntegerField(verbose_name='disclosure version')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='acknowledged at')),
                ('request_meta', models.JSONField(blank=True, default=dict, verbose_name='request metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='compliance.policyversion', verbose_name='policy version')),
            ],
            options={
                'verbose_name': 'policy acknowledgement',
                'verbose_name_plural': 'policy acknowledgements',
            },
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['status', 'display_order'], name='compliance_library_order'),
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['status', 'is_mandatory'], name='compliance_status_mandatory'),
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['version_family', 'version_number'], name='compliance_version_family'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('category__isnull', False), _connector='OR'), name='compliance_published_requires_category'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('effective_at__isnull', True), ('expires_at__gt', models.F('effective_at')), _connector='OR'), name='compliance_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(fields=('version_family', 'version_number'), name='compliance_policy_unique_version'),
        ),
        migrations.AddIndex(
            model_name='policyrequirement',
            index=models.Index(fields=['is_active', 'due_at'], name='compliance_requirement_due'),
        ),
        migrations.AddIndex(
            model_name='policyfile',
            index=models.Index(fields=['policy_version', 'role', 'is_active'], name='compliance_file_role'),
        ),
        migrations.AddConstraint(
            model_name='policyfile',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='compliance_file_has_bytes'),
        ),
        migrations.AddIndex(
            model_name='policyaudience',
            index=models.Index(fields=['kind', 'office'], name='compliance_aud_office'),
        ),
        migrations.AddIndex(
            model_name='policyaudience',
            index=models.Index(fields=['kind', 'role'], name='compliance_aud_role'),
        ),
        migrations.AddIndex(
            model_name='policyaudience',
            index=models.Index(fields=['kind', 'user'], name='compliance_aud_user'),
        ),
        migrations.AddConstraint(
            model_name='policyaudience',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'company'), ('office__isnull', True), ('role', ''), ('user__isnull', True)), models.Q(('kind', 'role'), ('office__isnull', True), ('user__isnull', True), models.Q(('role', ''), _negated=True)), models.Q(('kind__in', ['region', 'office']), ('office__isnull', False), ('role', ''), ('user__isnull', True)), models.Q(('kind', 'user'), ('office__isnull', True), ('role', ''), ('user__isnull', False)), _connector='OR'), name='compliance_audience_one_target_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='policyaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'company')), fields=('policy_version',), name='compliance_audience_one_company_row'),
        ),
        migrations.AddConstraint(
            model_name='policyaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'role')), fields=('policy_version', 'role'), name='compliance_audience_unique_role'),
        ),
        migrations.AddConstraint(
            model_name='policyaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('office__isnull', False)), fields=('policy_version', 'kind', 'office'), name='compliance_audience_unique_office'),
        ),
        migrations.AddConstraint(
            model_name='policyaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'user')), fields=('policy_version', 'user'), name='compliance_audience_unique_user'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgementwaiver',
            index=models.Index(fields=['policy_version', 'waived_at'], name='compliance_waiver_version'),
        ),
        migrations.AddConstraint(
            model_name='policyacknowledgementwaiver',
            constraint=models.UniqueConstraint(fields=('user', 'policy_version'), name='compliance_waiver_unique_user_version'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgement',
            index=models.Index(fields=['policy_version', 'acknowledged_at'], name='compliance_ack_version'),
        ),
        migrations.AddConstraint(
            model_name='policyacknowledgement',
            constraint=models.UniqueConstraint(fields=('user', 'policy_version'), name='compliance_ack_unique_user_version'),
        ),
    ]
