# Generated by Django 6.0.8 on 2026-09-13 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAcknowledgementCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('clerical', 'Clerical note'), ('revoke_waiver', 'Revoke waiver')], max_length=16, verbose_name='kind')),
                ('reason', models.TextField(verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'policy acknowledgement correction',
                'verbose_name_plural': 'policy acknowledgement corrections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('detail', 'Policy detail'), ('document', 'Policy document')], max_length=16, verbose_name='kind')),
                ('content_checksum', models.CharField(max_length=64, verbose_name='content checksum')),
                ('accessed_at', models.DateTimeField(auto_now=True, verbose_name='accessed at')),
            ],
            options={
                'verbose_name': 'policy version access',
                'verbose_name_plural': 'policy version accesses',
            },
        ),
        migrations.AddField(
            model_name='policyacknowledgement',
            name='disclosure_text',
            field=models.TextField(blank=True, verbose_name='disclosure text'),
        ),
        migrations.AddField(
            model_name='policyacknowledgementwaiver',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddConstraint(
            model_name='policyrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('policy_version',), name='compliance_one_active_requirement'),
        ),
        migrations.AddField(
            model_name='policyacknowledgementcorrection',
            name='corrected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_acknowledgement_corrections_made', to=settings.AUTH_USER_MODEL, verbose_name='corrected by'),
        ),
        migrations.AddField(
            model_name='policyacknowledgementcorrection',
            name='policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgement_corrections', to='compliance.policyversion', verbose_name='policy version'),
        ),
        migrations.AddField(
            model_name='policyacknowledgementcorrection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgement_corrections', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='policyversionaccess',
            name='policy_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='compliance.policyfile', verbose_name='policy file'),
        ),
        migrations.AddField(
            model_name='policyversionaccess',
            name='policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='compliance.policyversion', verbose_name='policy version'),
        ),
        migrations.AddField(
            model_name='policyversionaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_version_accesses', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgementcorrection',
            index=models.Index(fields=['policy_version', 'created_at'], name='compliance_correction_version'),
        ),
        migrations.AddIndex(
            model_name='policyversionaccess',
            index=models.Index(fields=['user', 'policy_version', 'kind'], name='compliance_access_lookup'),
        ),
        migrations.AddConstraint(
            model_name='policyversionaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'detail')), fields=('user', 'policy_version'), name='compliance_access_unique_detail'),
        ),
        migrations.AddConstraint(
            model_name='policyversionaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'document')), fields=('user', 'policy_version', 'policy_file'), name='compliance_access_unique_document'),
        ),
        migrations.AddConstraint(
            model_name='policyversionaccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'detail'), ('policy_file__isnull', True)), models.Q(('kind', 'document'), ('policy_file__isnull', False)), _connector='OR'), name='compliance_access_kind_file'),
        ),
    ]
