# Generated by Django 6.0.8 on 2026-08-28 14:47

import apps.feedback.models
import apps.user.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0026_operational_task_role_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('reference', models.CharField(blank=True, max_length=16, unique=True, verbose_name='reference')),
                ('category', models.CharField(choices=[('bug', 'Something is broken'), ('feature_idea', 'Idea or improvement'), ('content_correction', 'Something is wrong or out of date'), ('access_issue', 'I cannot get to something'), ('general_help', 'I need help')], max_length=32, verbose_name='category')),
                ('summary', models.CharField(max_length=160, verbose_name='summary')),
                ('description', models.TextField(verbose_name='description')),
                ('urgency', models.CharField(choices=[('blocking', 'I cannot work until this is fixed'), ('slowing', 'It is slowing me down'), ('minor', 'Minor — whenever you get to it')], max_length=16, verbose_name='urgency')),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('needs_info', 'Waiting for your reply'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='status')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Normal'), (4, 'Low')], default=3, verbose_name='priority')),
                ('page_url', models.CharField(blank=True, max_length=2000, verbose_name='page')),
                ('browser_metadata', models.JSONField(blank=True, default=dict, verbose_name='browser metadata')),
                ('submission_key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='submission key')),
                ('converted_task_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='converted task')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback', to=settings.AUTH_USER_MODEL, verbose_name='assignee')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_tickets', to='user.office', verbose_name='office at submission')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL, verbose_name='submitter')),
            ],
            options={
                'verbose_name': 'feedback ticket',
                'verbose_name_plural': 'feedback tickets',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('image', models.FileField(storage=apps.user.storage.private_storage, upload_to=apps.feedback.models.screenshot_upload_to, verbose_name='image')),
                ('display_name', models.CharField(max_length=200, verbose_name='display name')),
                ('media_type', models.CharField(max_length=100, verbose_name='media type')),
                ('byte_size', models.PositiveBigIntegerField(default=0, verbose_name='size in bytes')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='checksum')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='feedback.feedbackticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'feedback screenshot',
                'verbose_name_plural': 'feedback screenshots',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('body', models.TextField(verbose_name='body')),
                ('internal', models.BooleanField(default=False, help_text='Staff-only. Never shown to the submitter.', verbose_name='internal only')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_notes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='feedback.feedbackticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'feedback note',
                'verbose_name_plural': 'feedback notes',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['status', 'priority'], name='fb_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['office', 'status'], name='fb_office_status_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['submitter', '-created_at'], name='fb_submitter_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['assignee', 'status'], name='fb_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbackticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', False), ('status__in', ['closed'])), models.Q(models.Q(('status__in', ['closed']), _negated=True), ('closed_at__isnull', True)), _connector='OR'), name='feedback_closed_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='feedbackticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('summary', ''), _negated=True), models.Q(('description', ''), _negated=True)), name='feedback_requires_summary_and_description'),
        ),
        migrations.AddIndex(
            model_name='feedbackscreenshot',
            index=models.Index(fields=['ticket'], name='fb_shot_ticket_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacknote',
            index=models.Index(fields=['ticket', 'internal', 'created_at'], name='fb_note_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbacknote',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='feedback_note_requires_body'),
        ),
    ]
