# Generated by Django 6.0.8 on 2026-09-21 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0033_onboardingstreamstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('reference', models.CharField(blank=True, max_length=16, unique=True, verbose_name='reference')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent')], max_length=20, verbose_name='transaction type')),
                ('representation_type', models.CharField(choices=[('buyer', 'Buyer agency'), ('seller', 'Seller agency'), ('landlord', 'Landlord agency'), ('tenant', 'Tenant agency'), ('dual', 'Dual representation')], max_length=20, verbose_name='representation type')),
                ('property_snapshot', models.JSONField(blank=True, default=dict, help_text='Address and identity fields captured at write time.', verbose_name='property snapshot')),
                ('property_external_ref', models.CharField(blank=True, db_index=True, help_text='Opaque CRM/MLS property id for a later join.', max_length=64, verbose_name='property external reference')),
                ('mls_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='MLS number')),
                ('client_snapshots', models.JSONField(blank=True, default=list, help_text='Client presentation data; gated by field permission.', verbose_name='client snapshots')),
                ('client_external_refs', models.JSONField(blank=True, default=list, help_text='Opaque CRM contact ids for a later join.', verbose_name='client external references')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, null=True, verbose_name='list price')),
                ('contract_price', models.DecimalField(blank=True, decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, null=True, verbose_name='contract price')),
                ('acceptance_date', models.DateField(blank=True, null=True, verbose_name='acceptance date')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='closing date')),
                ('lender_ref', models.CharField(blank=True, max_length=128, verbose_name='lender reference')),
                ('title_ref', models.CharField(blank=True, max_length=128, verbose_name='title reference')),
                ('referral_ref', models.CharField(blank=True, max_length=128, verbose_name='referral reference')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preparing', 'Preparing'), ('under_contract', 'Under contract'), ('pending', 'Pending'), ('compliance_review', 'Compliance review'), ('ready_to_close', 'Ready to close'), ('closed', 'Closed'), ('archived', 'Archived'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn'), ('terminated', 'Terminated')], db_index=True, default='draft', max_length=32, verbose_name='status')),
                ('held_from_status', models.CharField(blank=True, help_text='Pipeline status restored when leaving On Hold.', max_length=32, verbose_name='held from status')),
                ('preparing_at', models.DateTimeField(blank=True, null=True, verbose_name='preparing at')),
                ('under_contract_at', models.DateTimeField(blank=True, null=True, verbose_name='under contract at')),
                ('pending_at', models.DateTimeField(blank=True, null=True, verbose_name='pending at')),
                ('compliance_review_at', models.DateTimeField(blank=True, null=True, verbose_name='compliance review at')),
                ('compliance_approved_at', models.DateTimeField(blank=True, help_text='Set when leaving Compliance Review for Ready to Close. Closing refuses without it.', null=True, verbose_name='compliance approved at')),
                ('ready_to_close_at', models.DateTimeField(blank=True, null=True, verbose_name='ready to close at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('on_hold_at', models.DateTimeField(blank=True, null=True, verbose_name='on hold at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='withdrawn at')),
                ('terminated_at', models.DateTimeField(blank=True, null=True, verbose_name='terminated at')),
                ('archive_reason', models.CharField(blank=True, max_length=255, verbose_name='archive reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_archived', to=settings.AUTH_USER_MODEL, verbose_name='archived by')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_transactions', to=settings.AUTH_USER_MODEL, verbose_name='assigned coordinator')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('office', models.ForeignKey(help_text='The node that owns this deal. Scope is read from it.', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='user.office', verbose_name='owning office')),
                ('primary_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_transactions', to=settings.AUTH_USER_MODEL, verbose_name='primary agent')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-created_at', '-pk'],
                'permissions': (('view_transaction_financials', 'Can view transaction list and contract prices'), ('view_transaction_clients', 'Can view transaction client snapshots')),
            },
        ),
        migrations.CreateModel(
            name='TransactionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('role', models.CharField(choices=[('primary_agent', 'Primary agent'), ('co_agent', 'Co-agent'), ('coordinator', 'Coordinator'), ('compliance_reviewer', 'Compliance reviewer')], max_length=32, verbose_name='role')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='transactions.transaction', verbose_name='transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_assignments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'transaction assignment',
                'verbose_name_plural': 'transaction assignments',
                'ordering': ['-assigned_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['office', 'status'], name='txn_office_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'closing_date'], name='txn_status_closing_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['primary_agent', 'status'], name='txn_primary_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['mls_number'], name='txn_mls_number_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['coordinator', 'status'], name='txn_coord_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['archived', 'cancelled', 'closed', 'compliance_review', 'draft', 'on_hold', 'pending', 'preparing', 'ready_to_close', 'terminated', 'under_contract', 'withdrawn'])), name='transaction_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'closed'), ('closed_at__isnull', False)), models.Q(models.Q(('status', 'closed'), _negated=True), models.Q(('status', 'archived'), _negated=True), ('closed_at__isnull', True)), models.Q(('status', 'archived'), ('closed_at__isnull', False), ('archived_at__isnull', False)), _connector='OR'), name='transaction_closed_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', False), ('status', 'archived')), models.Q(models.Q(('status', 'archived'), _negated=True), ('archived_at__isnull', True)), _connector='OR'), name='transaction_archived_at_matches_status'),
        ),
        migrations.AddIndex(
            model_name='transactionassignment',
            index=models.Index(fields=['user', 'ended_at'], name='txn_assign_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionassignment',
            index=models.Index(fields=['transaction', 'role', 'ended_at'], name='txn_assign_role_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('transaction', 'user', 'role'), name='txn_assignment_unique_active'),
        ),
        migrations.AddConstraint(
            model_name='transactionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('role__in', ['coordinator', 'primary_agent'])), fields=('transaction', 'role'), name='txn_assignment_singleton_active'),
        ),
    ]
