# Generated by Django 6.0.8 on 2026-09-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_transaction_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='submission_key',
            field=models.CharField(blank=True, help_text='Client-supplied idempotency key for create/prepare. Null until the first prepare attempt stamps one.', max_length=64, null=True, unique=True, verbose_name='submission key'),
        ),
    ]
