# Generated by Django 6.0.8 on 2026-09-21 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_create_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionKeyDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('date_type', models.CharField(choices=[('acceptance', 'Acceptance'), ('closing', 'Closing'), ('inspection', 'Inspection'), ('appraisal', 'Appraisal'), ('financing', 'Financing contingency'), ('earnest_money', 'Earnest money'), ('possession', 'Possession'), ('other', 'Other')], max_length=32, verbose_name='date type')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='label')),
                ('occurs_at', models.DateTimeField(blank=True, null=True, verbose_name='occurs at')),
                ('timezone', models.CharField(blank=True, max_length=64, verbose_name='timezone')),
                ('source', models.CharField(blank=True, max_length=64, verbose_name='source')),
                ('is_required', models.BooleanField(default=False, verbose_name='is required')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_key_dates_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='transactions.transactionkeydate', verbose_name='superseded by')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_dates', to='transactions.transaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'transaction key date',
                'verbose_name_plural': 'transaction key dates',
                'ordering': ['occurs_at', 'date_type', 'pk'],
                'indexes': [models.Index(fields=['transaction', 'date_type', 'ended_at'], name='txn_keydate_type_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('body', models.TextField(verbose_name='body')),
                ('visibility', models.CharField(choices=[('team', 'Team'), ('broker_compliance', 'Broker / compliance'), ('private_author', 'Private (author only)')], default='team', max_length=32, verbose_name='visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_notes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='transactions.transaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'transaction note',
                'verbose_name_plural': 'transaction notes',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['transaction', 'visibility', 'ended_at'], name='txn_note_vis_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('tenant', 'Tenant'), ('landlord', 'Landlord'), ('lender', 'Lender'), ('title', 'Title'), ('attorney', 'Attorney'), ('inspector', 'Inspector'), ('referral_agent', 'Referral agent'), ('co_party', 'Co-party')], max_length=32, verbose_name='role')),
                ('kind', models.CharField(choices=[('person', 'Person'), ('organization', 'Organization')], default='person', max_length=20, verbose_name='kind')),
                ('display_name', models.CharField(max_length=255, verbose_name='display name')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name='organization name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('representation', models.CharField(blank=True, choices=[('buyer', 'Buyer agency'), ('seller', 'Seller agency'), ('landlord', 'Landlord agency'), ('tenant', 'Tenant agency'), ('dual', 'Dual representation')], max_length=20, verbose_name='representation')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='valid until')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen presentation fields captured on each write.', verbose_name='snapshot')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_parties_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='transactions.transaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'transaction party',
                'verbose_name_plural': 'transaction parties',
                'ordering': ['role', '-is_primary', 'display_name', 'pk'],
                'indexes': [models.Index(fields=['transaction', 'role', 'ended_at'], name='txn_party_role_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('is_primary', True), ('role__in', ['buyer', 'landlord', 'lender', 'seller', 'tenant', 'title'])), fields=('transaction', 'role'), name='txn_party_unique_primary_role')],
            },
        ),
        migrations.CreateModel(
            name='TransactionPropertySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('snapshot', models.JSONField(default=dict, verbose_name='snapshot')),
                ('mls_number', models.CharField(blank=True, max_length=64, verbose_name='MLS number')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('change_summary', models.JSONField(blank=True, default=list, help_text='Allowlisted field keys that changed in this revision.', verbose_name='change summary')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_property_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_snapshots', to='transactions.transaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'transaction property snapshot',
                'verbose_name_plural': 'transaction property snapshots',
                'ordering': ['-recorded_at', '-pk'],
                'indexes': [models.Index(fields=['transaction', '-recorded_at'], name='txn_prop_snap_txn_idx')],
            },
        ),
    ]
