# Generated by Django 6.0.8 on 2026-09-21 19:23

import apps.transactions.models
import apps.user.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_workspace_parties_dates_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('category', models.CharField(choices=[('addendum', 'Addendum'), ('closing', 'Closing'), ('disclosure', 'Disclosure'), ('inspection', 'Inspection'), ('other', 'Other'), ('purchase_agreement', 'Purchase agreement')], default='other', max_length=32, verbose_name='category')),
                ('requirement', models.CharField(choices=[('optional', 'Optional'), ('required', 'Required')], default='optional', max_length=16, verbose_name='requirement')),
                ('title', models.CharField(max_length=180, verbose_name='title')),
                ('retention_policy', models.CharField(choices=[('custom', 'Custom date'), ('deal_close_plus_3y', 'Three years after close'), ('deal_close_plus_7y', 'Seven years after close'), ('indefinite', 'Indefinite')], default='deal_close_plus_7y', max_length=32, verbose_name='retention policy')),
                ('retain_until', models.DateField(blank=True, null=True, verbose_name='retain until')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_documents_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transactions.transaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'transaction document',
                'verbose_name_plural': 'transaction documents',
                'ordering': ['category', 'title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TransactionDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='version number')),
                ('original_name', models.CharField(max_length=255, verbose_name='original name')),
                ('display_name', models.CharField(max_length=180, verbose_name='display name')),
                ('file', models.FileField(max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.transactions.models._transaction_document_upload_to, verbose_name='file')),
                ('media_type', models.CharField(max_length=120, verbose_name='media type')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='size in bytes')),
                ('checksum', models.CharField(max_length=64, verbose_name='checksum')),
                ('processing_state', models.CharField(choices=[('pending', 'Processing'), ('ready', 'Ready'), ('quarantined', 'Quarantined'), ('failed', 'Processing failed')], default='pending', max_length=16, verbose_name='processing state')),
                ('processing_note', models.CharField(blank=True, max_length=255, verbose_name='processing note')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('signature_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending signature'), ('signed', 'Signed')], default='none', max_length=16, verbose_name='signature status')),
                ('compliance_status', models.CharField(choices=[('approved', 'Approved'), ('in_review', 'In review'), ('none', 'None'), ('rejected', 'Rejected')], default='none', max_length=16, verbose_name='compliance status')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='locked at')),
                ('lock_reason', models.CharField(blank=True, max_length=64, verbose_name='lock reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='transactions.transactiondocument', verbose_name='document')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_document_versions_locked', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_document_versions_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'transaction document version',
                'verbose_name_plural': 'transaction document versions',
                'ordering': ['-version_number', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TransactionDocumentReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('body', models.TextField(verbose_name='body')),
                ('visibility', models.CharField(choices=[('team', 'Team'), ('broker_compliance', 'Broker / compliance'), ('private_author', 'Private (author only)')], default='team', max_length=32, verbose_name='visibility')),
                ('resolution_state', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16, verbose_name='resolution state')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_document_review_comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_document_reviews_resolved', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='transactions.transactiondocumentversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'transaction document review comment',
                'verbose_name_plural': 'transaction document review comments',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='transactiondocument',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transactiondocumentversion', verbose_name='current version'),
        ),
        migrations.AddIndex(
            model_name='transactiondocumentversion',
            index=models.Index(fields=['document', 'is_active', 'processing_state'], name='txn_doc_ver_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactiondocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='txn_doc_unique_document_version'),
        ),
        migrations.AddConstraint(
            model_name='transactiondocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='txn_doc_version_has_bytes'),
        ),
        migrations.AddIndex(
            model_name='transactiondocumentreviewcomment',
            index=models.Index(fields=['version', 'visibility', 'ended_at'], name='txn_doc_review_vis_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondocument',
            index=models.Index(fields=['transaction', 'ended_at', 'category'], name='txn_doc_txn_active_cat_idx'),
        ),
    ]
