# Generated by Django 6.0.8 on 2026-09-22 08:44

import apps.transactions.models
import apps.user.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignaturePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('title', models.CharField(max_length=180, verbose_name='title')),
                ('status', models.CharField(choices=[('cancelled', 'Cancelled'), ('completed', 'Completed'), ('declined', 'Declined'), ('draft', 'Draft'), ('expired', 'Expired'), ('in_progress', 'In progress'), ('sent', 'Sent')], db_index=True, default='draft', max_length=16, verbose_name='status')),
                ('routing_mode', models.CharField(choices=[('ordered', 'Ordered'), ('parallel', 'Parallel')], default='ordered', max_length=16, verbose_name='routing mode')),
                ('disclosure_version', models.CharField(blank=True, default='', max_length=64, verbose_name='disclosure version')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_packages_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_packages', to='transactions.transaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'signature package',
                'verbose_name_plural': 'signature packages',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SignaturePackageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('source_checksum', models.CharField(max_length=64, verbose_name='source checksum')),
                ('page_count', models.PositiveIntegerField(default=1, verbose_name='page count')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transactions.signaturepackage', verbose_name='package')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_package_documents', to='transactions.transactiondocumentversion', verbose_name='document version')),
            ],
            options={
                'verbose_name': 'signature package document',
                'verbose_name_plural': 'signature package documents',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SignatureArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('kind', models.CharField(choices=[('certificate_of_completion', 'Certificate of completion'), ('signed_pdf', 'Signed PDF')], default='signed_pdf', max_length=32, verbose_name='kind')),
                ('display_name', models.CharField(max_length=180, verbose_name='display name')),
                ('file', models.FileField(max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.transactions.models._signature_artifact_upload_to, verbose_name='file')),
                ('media_type', models.CharField(default='application/pdf', max_length=120, verbose_name='media type')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='size in bytes')),
                ('checksum', models.CharField(max_length=64, verbose_name='checksum')),
                ('source_checksum', models.CharField(blank=True, default='', max_length=64, verbose_name='source checksum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='transactions.signaturepackage', verbose_name='package')),
                ('package_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='transactions.signaturepackagedocument', verbose_name='package document')),
            ],
            options={
                'verbose_name': 'signature artifact',
                'verbose_name_plural': 'signature artifacts',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SignaturePackageSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('role_label', models.CharField(max_length=64, verbose_name='role label')),
                ('display_name', models.CharField(max_length=255, verbose_name='display name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('delivery_method', models.CharField(choices=[('email', 'Email magic link'), ('hub', 'Hub user')], default='email', max_length=16, verbose_name='delivery method')),
                ('routing_order', models.PositiveIntegerField(default=1, verbose_name='routing order')),
                ('status', models.CharField(choices=[('declined', 'Declined'), ('expired', 'Expired'), ('invited', 'Invited'), ('pending', 'Pending'), ('signed', 'Signed'), ('viewed', 'Viewed')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('invited_at', models.DateTimeField(blank=True, null=True, verbose_name='invited at')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='viewed at')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='signed at')),
                ('declined_at', models.DateTimeField(blank=True, null=True, verbose_name='declined at')),
                ('decline_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='decline reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='transactions.signaturepackage', verbose_name='package')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_signers', to='transactions.transactionparty', verbose_name='transaction party')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_signature_signers', to=settings.AUTH_USER_MODEL, verbose_name='hub user')),
            ],
            options={
                'verbose_name': 'signature package signer',
                'verbose_name_plural': 'signature package signers',
                'ordering': ['routing_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SignaturePackageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('field_type', models.CharField(choices=[('date', 'Date'), ('initials', 'Initials'), ('signature', 'Signature'), ('text', 'Text')], default='signature', max_length=16, verbose_name='field type')),
                ('page', models.PositiveIntegerField(default=1, verbose_name='page')),
                ('x', models.FloatField(verbose_name='x')),
                ('y', models.FloatField(verbose_name='y')),
                ('w', models.FloatField(verbose_name='width')),
                ('h', models.FloatField(verbose_name='height')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='transactions.signaturepackagedocument', verbose_name='package document')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='transactions.signaturepackage', verbose_name='package')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='transactions.signaturepackagesigner', verbose_name='signer')),
            ],
            options={
                'verbose_name': 'signature package field',
                'verbose_name_plural': 'signature package fields',
                'ordering': ['document_id', 'page', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SignatureAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='token hash')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumed at')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='last sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='transactions.signaturepackagesigner', verbose_name='signer')),
            ],
            options={
                'verbose_name': 'signature access token',
                'verbose_name_plural': 'signature access tokens',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SignatureSigningIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('package_version', models.CharField(max_length=64, verbose_name='package version token')),
                ('source_checksums', models.JSONField(default=dict, verbose_name='source checksums')),
                ('session_key_hash', models.CharField(max_length=64, verbose_name='session key hash')),
                ('access_token_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='access token hash')),
                ('request_ip_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='request IP hash')),
                ('request_ua_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='request user-agent hash')),
                ('disclosure_version', models.CharField(max_length=64, verbose_name='disclosure version')),
                ('consent_accepted_at', models.DateTimeField(verbose_name='consent accepted at')),
                ('status', models.CharField(choices=[('cancelled', 'Cancelled'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('pending', 'Pending')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumed at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_signing_intents', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_intents', to='transactions.signaturepackage', verbose_name='package')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_intents', to='transactions.signaturepackagesigner', verbose_name='signer')),
            ],
            options={
                'verbose_name': 'signature signing intent',
                'verbose_name_plural': 'signature signing intents',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('method', models.CharField(default='hub_embedded', max_length=32, verbose_name='method')),
                ('disclosure_version', models.CharField(max_length=64, verbose_name='disclosure version')),
                ('source_checksums', models.JSONField(default=dict, verbose_name='source checksums')),
                ('field_values', models.JSONField(blank=True, default=dict, verbose_name='field values')),
                ('signed_date_value', models.CharField(blank=True, default='', max_length=64, verbose_name='signed date value')),
                ('appearance_file', models.FileField(blank=True, default='', max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.transactions.models._signature_appearance_upload_to, verbose_name='signature appearance')),
                ('initials_file', models.FileField(blank=True, default='', max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.transactions.models._signature_initials_upload_to, verbose_name='initials appearance')),
                ('appearance_checksum', models.CharField(blank=True, default='', max_length=64, verbose_name='appearance checksum')),
                ('request_ip_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='request IP hash')),
                ('request_ua_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='request user-agent hash')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='signed at')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_records', to='transactions.signaturepackage', verbose_name='package')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_records', to='transactions.signaturepackagesigner', verbose_name='signer')),
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature_record', to='transactions.signaturesigningintent', verbose_name='signing intent')),
            ],
            options={
                'verbose_name': 'signature record',
                'verbose_name_plural': 'signature records',
                'ordering': ['-signed_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='signaturepackage',
            index=models.Index(fields=['transaction', 'status', '-created_at'], name='txn_sig_pkg_txn_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='signaturepackagedocument',
            constraint=models.UniqueConstraint(fields=('package', 'version'), name='txn_sig_pkg_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='signatureartifact',
            constraint=models.UniqueConstraint(condition=models.Q(('package_document__isnull', False)), fields=('package', 'package_document', 'kind'), name='txn_sig_unique_doc_artifact_kind'),
        ),
        migrations.AddConstraint(
            model_name='signatureartifact',
            constraint=models.UniqueConstraint(condition=models.Q(('package_document__isnull', True)), fields=('package', 'kind'), name='txn_sig_unique_pkg_artifact_kind'),
        ),
        migrations.AddIndex(
            model_name='signaturepackagesigner',
            index=models.Index(fields=['package', 'routing_order', 'status'], name='txn_sig_signer_route_idx'),
        ),
        migrations.AddConstraint(
            model_name='signaturepackagesigner',
            constraint=models.UniqueConstraint(fields=('package', 'email'), name='txn_sig_pkg_unique_signer_email'),
        ),
        migrations.AddConstraint(
            model_name='signaturepackagefield',
            constraint=models.UniqueConstraint(fields=('package', 'name'), name='txn_sig_pkg_unique_field_name'),
        ),
        migrations.AddConstraint(
            model_name='signaturepackagefield',
            constraint=models.CheckConstraint(condition=models.Q(('page__gte', 1), ('w__gt', 0), ('h__gt', 0), ('x__gte', 0), ('y__gte', 0)), name='txn_sig_field_bounds_positive'),
        ),
        migrations.AddIndex(
            model_name='signatureaccesstoken',
            index=models.Index(fields=['signer', '-created_at'], name='txn_sig_token_signer_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturesigningintent',
            index=models.Index(fields=['package', 'signer', 'status'], name='txn_sig_intent_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='signaturerecord',
            constraint=models.UniqueConstraint(fields=('package', 'signer'), name='txn_sig_unique_package_signer'),
        ),
    ]
