# Generated by Django 6.0.8 on 2026-08-31 04:30

import apps.inventory.models
import apps.user.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0027_feedback_triage_role_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('signage', 'Signage'), ('marketing', 'Marketing materials'), ('keys_lockbox', 'Keys and lockboxes'), ('vehicle', 'Vehicle'), ('office_supplies', 'Office supplies'), ('other', 'Other')], max_length=40, verbose_name='category')),
                ('tracking_mode', models.CharField(choices=[('serialized', 'Individually serialized'), ('pooled', 'Pooled quantity')], default='serialized', max_length=20, verbose_name='tracking mode')),
                ('asset_id', models.CharField(blank=True, help_text='Brokerage asset tag. Required for serialized items.', max_length=64, verbose_name='asset id')),
                ('serial_number', models.CharField(blank=True, max_length=128, verbose_name='serial number')),
                ('total_quantity', models.PositiveIntegerField(default=1, help_text='Authoritative on-hand count for pooled stock. Serialized items always have an effective quantity of one.', verbose_name='total quantity')),
                ('condition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('needs_repair', 'Needs repair')], max_length=20, verbose_name='condition')),
                ('availability_state', models.CharField(choices=[('active', 'Active'), ('available', 'Available for reservation'), ('temporarily_unavailable', 'Temporarily unavailable'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('retired', 'Retired')], default='available', max_length=32, verbose_name='availability state')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='storage location')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('internal_notes', models.TextField(blank=True, help_text='Staff-only. Never serialized without the sensitive grant.', verbose_name='internal notes')),
                ('photo', models.FileField(blank=True, max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.inventory.models.inventory_photo_upload_to, verbose_name='photo')),
                ('photo_is_public', models.BooleanField(default=False, help_text='When false the photo is internal-only and served through an authorized download view.', verbose_name='photo approved for public display')),
                ('replacement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='replacement value')),
                ('replacement_currency', models.CharField(blank=True, default='USD', max_length=3, verbose_name='replacement currency')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='activated at')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='retired at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner_office', models.ForeignKey(help_text='The assignable office that owns this record. Scope is read from it.', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='user.office', verbose_name='owning office')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
                'ordering': ['name', 'pk'],
                'permissions': (('manage_inventory', 'Can manage scoped inventory items'), ('view_inventory_sensitive', 'Can view inventory serial numbers, valuation, and internal notes')),
            },
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='performed at')),
                ('from_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfers_from', to='user.office', verbose_name='from office')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.inventoryitem', verbose_name='item')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transfers_performed', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
                ('to_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfers_to', to='user.office', verbose_name='to office')),
            ],
            options={
                'verbose_name': 'inventory transfer',
                'verbose_name_plural': 'inventory transfers',
                'ordering': ['-performed_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['owner_office', 'availability_state'], name='inv_item_office_state_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inv_item_category_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tracking_mode'], name='inv_item_tracking_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['owner_office', 'category', 'availability_state'], name='inv_item_office_cat_state'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['name'], name='inv_item_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='inventory_item_requires_name'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('total_quantity__gte', 0)), name='inventory_item_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('replacement_value__isnull', True), ('replacement_value__gte', Decimal('0')), _connector='OR'), name='inventory_item_replacement_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tracking_mode', 'serialized'), _negated=True), ('total_quantity', 1), _connector='OR'), name='inventory_item_serialized_quantity_one'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tracking_mode', 'pooled'), _negated=True), ('total_quantity__gte', 1), _connector='OR'), name='inventory_item_pooled_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tracking_mode', 'serialized'), _negated=True), models.Q(('asset_id', ''), _negated=True), _connector='OR'), name='inventory_item_serialized_requires_asset_id'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('tracking_mode', 'serialized'), models.Q(('asset_id', ''), ('serial_number', '')), _connector='OR'), name='inventory_item_pooled_no_identifiers'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('availability_state__in', ['retired']), ('retired_at__isnull', False)), models.Q(models.Q(('availability_state__in', ['retired']), _negated=True), ('retired_at__isnull', True)), _connector='OR'), name='inventory_item_retired_at_matches_state'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('asset_id', ''), _negated=True), fields=('owner_office', 'asset_id'), name='inventory_item_unique_asset_id_per_office'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('owner_office', 'serial_number'), name='inventory_item_unique_serial_per_office'),
        ),
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['item', '-performed_at'], name='inv_xfer_item_time'),
        ),
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['from_office'], name='inv_xfer_from_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['to_office'], name='inv_xfer_to_idx'),
        ),
    ]
