# Generated by Django 6.0.8 on 2026-08-31 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('user', '0028_inventory_role_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name', 'pk'], 'permissions': (('manage_inventory', 'Can manage scoped inventory items'), ('view_inventory_sensitive', 'Can view inventory serial numbers, valuation, and internal notes'), ('reserve_on_behalf', 'Can create inventory reservations for other users'), ('approve_reservations', 'Can approve or deny inventory reservations'), ('override_reservations', 'Can override inventory reservation policy with a reason')), 'verbose_name': 'inventory item', 'verbose_name_plural': 'inventory items'},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='When true, new reservations start as requested and wait for office approval. When false, available reservations auto-confirm.', verbose_name='requires office approval'),
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('reference', models.CharField(blank=True, max_length=24, unique=True, verbose_name='reference')),
                ('office_name', models.CharField(max_length=200, verbose_name='office name snapshot')),
                ('item_name', models.CharField(max_length=200, verbose_name='item name snapshot')),
                ('starts_at', models.DateTimeField(verbose_name='pickup starts at')),
                ('ends_at', models.DateTimeField(verbose_name='return ends at')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('purpose', models.CharField(blank=True, max_length=240, verbose_name='business purpose')),
                ('status', models.CharField(choices=[('requested', 'Requested — awaiting office approval'), ('confirmed', 'Confirmed'), ('ready_for_pickup', 'Ready for pickup'), ('checked_out', 'Checked out'), ('returned', 'Returned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('denied', 'Denied'), ('overdue', 'Overdue'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='confirmed', max_length=32, verbose_name='status')),
                ('instructions_snapshot', models.TextField(blank=True, verbose_name='pickup/return instructions snapshot')),
                ('storage_location_snapshot', models.CharField(blank=True, max_length=200, verbose_name='storage location snapshot')),
                ('submission_key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='submission key')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancel_reason', models.CharField(blank=True, max_length=240, verbose_name='cancel reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservations_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservations_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventoryitem', verbose_name='item')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='user.office', verbose_name='office at reservation')),
                ('owner', models.ForeignKey(help_text='The agent the reservation belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'inventory reservation',
                'verbose_name_plural': 'inventory reservations',
                'ordering': ['-starts_at', '-pk'],
                'indexes': [models.Index(fields=['item', 'status', 'starts_at', 'ends_at'], name='inv_rsv_item_status_range'), models.Index(fields=['owner', '-starts_at'], name='inv_rsv_owner_starts'), models.Index(fields=['office', 'status'], name='inv_rsv_office_status'), models.Index(fields=['status', 'ends_at'], name='inv_rsv_status_ends')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='inventory_reservation_quantity_positive'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='inventory_reservation_ends_after_starts'), models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('status', 'cancelled')), models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_at__isnull', True)), _connector='OR'), name='inventory_reservation_cancelled_at_matches')],
            },
        ),
    ]
