# Generated by Django 6.0.8 on 2026-08-31 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_reservation_role_grants'),
        ('user', '0028_inventory_role_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreservation',
            name='over_allocation_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='over-allocation approved at'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='over_allocation_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_over_allocations_approved', to=settings.AUTH_USER_MODEL, verbose_name='over-allocation approved by'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='over_allocation_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='over-allocation reason'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(condition=models.Q(('status__in', ['checked_out', 'confirmed', 'overdue', 'ready_for_pickup', 'requested'])), fields=['item', 'starts_at', 'ends_at'], name='inv_rsv_capacity_overlap'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('over_allocation_approved_at__isnull', False), models.Q(('over_allocation_reason', ''), _negated=True)), models.Q(('over_allocation_approved_at__isnull', True), ('over_allocation_reason', '')), _connector='OR'), name='inventory_reservation_over_allocation_recorded'),
        ),
    ]
