from django.urls import path

from apps.reservations import views

urlpatterns = [
    path("rooms", views.room_availability, name="room_availability"),
    path(
        "rooms/reservations/new",
        views.room_reservation_new,
        name="room_reservation_new",
    ),
    path(
        "rooms/reservations",
        views.room_reservation_create,
        name="room_reservation_create",
    ),
    path(
        "operations/rooms",
        views.space_administration,
        name="space_administration",
    ),
    path(
        "operations/rooms/create",
        views.space_administration_create,
        name="space_administration_create",
    ),
    path(
        "operations/rooms/<uuid:public_id>",
        views.space_administration_workspace,
        name="space_administration_workspace",
    ),
    path(
        "operations/rooms/<uuid:public_id>/update",
        views.space_administration_update,
        name="space_administration_update",
    ),
    path(
        "operations/rooms/<uuid:public_id>/activation",
        views.space_administration_activation,
        name="space_administration_activation",
    ),
    path(
        "operations/rooms/<uuid:public_id>/retire",
        views.space_administration_retire,
        name="space_administration_retire",
    ),
    path(
        "operations/rooms/<uuid:public_id>/schedule",
        views.space_administration_schedule,
        name="space_administration_schedule",
    ),
    path(
        "operations/rooms/<uuid:public_id>/blocks",
        views.space_administration_block_create,
        name="space_administration_block_create",
    ),
    path(
        "operations/rooms/blocks/<uuid:public_id>/update",
        views.space_administration_block_update,
        name="space_administration_block_update",
    ),
    path(
        "operations/rooms/blocks/<uuid:public_id>/delete",
        views.space_administration_block_delete,
        name="space_administration_block_delete",
    ),
    path(
        "operations/rooms/bookings/<uuid:public_id>/move",
        views.space_administration_booking_move,
        name="space_administration_booking_move",
    ),
    path(
        "operations/rooms/bookings/<uuid:public_id>/cancel",
        views.space_administration_booking_cancel,
        name="space_administration_booking_cancel",
    ),
]
