# Generated by Django 6.0.8 on 2026-09-10 13:34

import apps.marketing.models
import apps.user.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0029_office_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=80, verbose_name='label')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='display order')),
                ('is_system', models.BooleanField(default=False, editable=False, verbose_name='system category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'marketing category',
                'verbose_name_plural': 'marketing categories',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MarketingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, verbose_name='slug')),
                ('title', models.CharField(max_length=180, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('usage_instructions', models.TextField(blank=True, verbose_name='usage instructions')),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('guideline', 'Guideline'), ('template', 'Template'), ('flyer', 'Flyer'), ('email_signature', 'Email signature'), ('vendor_guidance', 'Vendor guidance'), ('campaign', 'Campaign asset')], max_length=32, verbose_name='asset type')),
                ('jurisdiction_state_codes', models.JSONField(blank=True, default=list, help_text='Empty means all jurisdictions.', verbose_name='jurisdiction state codes')),
                ('brand_codes', models.JSONField(blank=True, default=list, help_text='Empty means all brands.', verbose_name='brand codes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16, verbose_name='status')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='publishes at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='published at')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='archived at')),
                ('version_family', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Shared across successive versions of the same asset.', verbose_name='version family')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='version number')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_assets_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_assets', to='user.office', verbose_name='owning office')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_assets_edited', to=settings.AUTH_USER_MODEL, verbose_name='last edited by')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='marketing.marketingcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'marketing asset',
                'verbose_name_plural': 'marketing assets',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MarketingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('export', 'Approved export'), ('source', 'Editable source'), ('preview', 'Generated preview')], max_length=16, verbose_name='role')),
                ('display_name', models.CharField(max_length=180, verbose_name='display name')),
                ('file', models.FileField(max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.marketing.models._file_upload_to, verbose_name='file')),
                ('media_type', models.CharField(max_length=120, verbose_name='media type')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='size in bytes')),
                ('checksum', models.CharField(max_length=64, verbose_name='checksum')),
                ('processing_state', models.CharField(choices=[('pending', 'Processing'), ('ready', 'Ready'), ('quarantined', 'Quarantined'), ('failed', 'Processing failed')], default='pending', max_length=16, verbose_name='processing state')),
                ('processing_note', models.CharField(blank=True, max_length=255, verbose_name='processing note')),
                ('variants', models.JSONField(blank=True, default=dict, verbose_name='variants')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='marketing.marketingasset', verbose_name='asset')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_files_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'marketing file',
                'verbose_name_plural': 'marketing files',
                'ordering': ['role', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MarketingAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('company', 'Everyone at the brokerage'), ('role', 'Everyone holding a role'), ('region', 'A region and the offices under it'), ('office', 'One office only'), ('user', 'One named person')], max_length=16, verbose_name='kind')),
                ('role', models.CharField(blank=True, max_length=64, verbose_name='role code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='marketing.marketingasset', verbose_name='asset')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_audiences', to='user.office', verbose_name='office')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_audiences', to=settings.AUTH_USER_MODEL, verbose_name='person')),
            ],
            options={
                'verbose_name': 'marketing audience',
                'verbose_name_plural': 'marketing audiences',
                'indexes': [models.Index(fields=['kind', 'office'], name='marketing_aud_office'), models.Index(fields=['kind', 'role'], name='marketing_aud_role'), models.Index(fields=['kind', 'user'], name='marketing_aud_user')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'company'), ('office__isnull', True), ('role', ''), ('user__isnull', True)), models.Q(('kind', 'role'), ('office__isnull', True), ('user__isnull', True), models.Q(('role', ''), _negated=True)), models.Q(('kind__in', ['region', 'office']), ('office__isnull', False), ('role', ''), ('user__isnull', True)), models.Q(('kind', 'user'), ('office__isnull', True), ('role', ''), ('user__isnull', False)), _connector='OR'), name='marketing_audience_one_target_per_kind'), models.UniqueConstraint(condition=models.Q(('kind', 'company')), fields=('asset',), name='marketing_audience_one_company_row'), models.UniqueConstraint(condition=models.Q(('kind', 'role')), fields=('asset', 'role'), name='marketing_audience_unique_role'), models.UniqueConstraint(condition=models.Q(('office__isnull', False)), fields=('asset', 'kind', 'office'), name='marketing_audience_unique_office'), models.UniqueConstraint(condition=models.Q(('kind', 'user')), fields=('asset', 'user'), name='marketing_audience_unique_user')],
            },
        ),
        migrations.AddIndex(
            model_name='marketingasset',
            index=models.Index(fields=['status', 'display_order'], name='marketing_library_order'),
        ),
        migrations.AddIndex(
            model_name='marketingasset',
            index=models.Index(fields=['status', 'asset_type'], name='marketing_status_type'),
        ),
        migrations.AddIndex(
            model_name='marketingasset',
            index=models.Index(fields=['version_family', 'version_number'], name='marketing_version_family'),
        ),
        migrations.AddConstraint(
            model_name='marketingasset',
            constraint=models.UniqueConstraint(fields=('owner_office', 'slug'), name='marketing_asset_unique_slug_per_office'),
        ),
        migrations.AddConstraint(
            model_name='marketingasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('category__isnull', False), _connector='OR'), name='marketing_published_requires_category'),
        ),
        migrations.AddConstraint(
            model_name='marketingasset',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('publish_at__isnull', True), ('expires_at__gt', models.F('publish_at')), _connector='OR'), name='marketing_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='marketingasset',
            constraint=models.UniqueConstraint(fields=('version_family', 'version_number'), name='marketing_asset_unique_version'),
        ),
        migrations.AddIndex(
            model_name='marketingfile',
            index=models.Index(fields=['asset', 'role', 'is_active'], name='marketing_file_role'),
        ),
        migrations.AddConstraint(
            model_name='marketingfile',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='marketing_file_has_bytes'),
        ),
    ]
