from django.urls import path

from .administration_views import (
    training_certificate_approve,
    training_create,
    training_duplicate_version,
    training_edit,
    training_lifecycle,
    training_media_manager,
    training_media_remove,
    training_media_reorder,
    training_media_replace,
    training_media_upload,
    training_modules_save,
    training_new,
    training_progress_correct,
    training_quiz_save,
    training_recipient_search,
    training_session_save,
    training_update,
)
from .views import (
    training_certificate,
    training_detail,
    training_learning,
    training_media,
    training_progress,
    training_quiz_submit,
    training_session_register,
)

urlpatterns = [
    path("training-learning", training_learning, name="training_learning"),
    path(
        "training-learning/<int:content_id>",
        training_detail,
        name="training_detail",
    ),
    path(
        "training-learning/<int:content_id>/progress",
        training_progress,
        name="training_progress",
    ),
    path(
        "training-learning/<int:content_id>/quiz/submit",
        training_quiz_submit,
        name="training_quiz_submit",
    ),
    path(
        "training-learning/<int:content_id>/session/register",
        training_session_register,
        name="training_session_register",
    ),
    path(
        "training-learning/<int:content_id>/certificate",
        training_certificate,
        name="training_certificate",
    ),
    path(
        "training-learning/media/<int:media_id>",
        training_media,
        name="training_media",
    ),
    path(
        "operations/training/recipients",
        training_recipient_search,
        name="training_recipient_search",
    ),
    path(
        "operations/training/new",
        training_new,
        name="training_new",
    ),
    path(
        "operations/training/create",
        training_create,
        name="training_create",
    ),
    path(
        "operations/training/<int:content_id>/edit",
        training_edit,
        name="training_edit",
    ),
    path(
        "operations/training/<int:content_id>/save",
        training_update,
        name="training_update",
    ),
    path(
        "operations/training/<int:content_id>/lifecycle",
        training_lifecycle,
        name="training_lifecycle",
    ),
    path(
        "operations/training/<int:content_id>/duplicate-version",
        training_duplicate_version,
        name="training_duplicate_version",
    ),
    path(
        "operations/training/<int:content_id>/quiz/save",
        training_quiz_save,
        name="training_quiz_save",
    ),
    path(
        "operations/training/<int:content_id>/session/save",
        training_session_save,
        name="training_session_save",
    ),
    path(
        "operations/training/<int:content_id>/modules/save",
        training_modules_save,
        name="training_modules_save",
    ),
    path(
        "operations/training/<int:content_id>/progress/correct",
        training_progress_correct,
        name="training_progress_correct",
    ),
    path(
        "operations/training/certificates/<int:certificate_id>/approve",
        training_certificate_approve,
        name="training_certificate_approve",
    ),
    path(
        "operations/training/<int:content_id>/media",
        training_media_manager,
        name="training_media_manager",
    ),
    path(
        "operations/training/<int:content_id>/media/upload",
        training_media_upload,
        name="training_media_upload",
    ),
    path(
        "operations/training/<int:content_id>/media/reorder",
        training_media_reorder,
        name="training_media_reorder",
    ),
    path(
        "operations/training/media/<int:media_id>/replace",
        training_media_replace,
        name="training_media_replace",
    ),
    path(
        "operations/training/media/<int:media_id>/remove",
        training_media_remove,
        name="training_media_remove",
    ),
]

# Index is wired through OPERATIONS_VIEWS in apps.web.views.
