# Generated by Django 6.0.8 on 2026-08-23 15:29

import apps.contract.models
import apps.user.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0025_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('stable_key', models.SlugField(help_text='Immutable machine key for the template family.', max_length=80, unique=True, verbose_name='stable key')),
                ('name', models.CharField(max_length=180, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'contract template',
                'verbose_name_plural': 'contract templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('family_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Stable identity for the contract family. Amendments and replacements share this id and increment version_number.', verbose_name='family id')),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Monotonic revision within the family. Starts at 1.', verbose_name='version number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for review'), ('sent', 'Sent to agent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('active', 'Active'), ('superseded', 'Superseded'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('generation_error', 'Generation error')], db_index=True, default='draft', max_length=32, verbose_name='status')),
                ('effective_on', models.DateField(verbose_name='effective on')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='expires on')),
                ('agent_split_percent', models.DecimalField(blank=True, decimal_places=3, help_text='Percentage points (0–100), three decimal places. Unit: percent.', max_digits=6, null=True, verbose_name='agent split percent')),
                ('office_split_percent', models.DecimalField(blank=True, decimal_places=3, help_text='Percentage points (0–100), three decimal places. Unit: percent.', max_digits=6, null=True, verbose_name='office split percent')),
                ('transaction_fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, null=True, verbose_name='transaction fee amount')),
                ('transaction_fee_percent', models.DecimalField(blank=True, decimal_places=3, help_text='Percentage points (0–100), three decimal places. Unit: percent.', max_digits=6, null=True, verbose_name='transaction fee percent')),
                ('annual_cap_amount', models.DecimalField(blank=True, decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, null=True, verbose_name='annual cap amount')),
                ('mentor_percent', models.DecimalField(blank=True, decimal_places=3, help_text='Percentage points (0–100), three decimal places. Unit: percent.', max_digits=6, null=True, verbose_name='mentor percent')),
                ('mentor_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, null=True, verbose_name='mentor fixed amount')),
                ('mentor_cap_amount', models.DecimalField(blank=True, decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, null=True, verbose_name='mentor cap amount')),
                ('mentor_basis', models.CharField(blank=True, choices=[('gross_commission', 'Gross commission income'), ('agent_side_before_fees', 'Agent side before fees'), ('agent_side_after_fees', 'Agent side after fees'), ('fixed_only', 'Fixed amount only')], max_length=32, verbose_name='mentor basis')),
                ('mentor_notes', models.CharField(blank=True, max_length=500, verbose_name='mentor notes')),
                ('referral_percent', models.DecimalField(blank=True, decimal_places=3, help_text='Percentage points (0–100), three decimal places. Unit: percent.', max_digits=6, null=True, verbose_name='referral percent')),
                ('referral_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, null=True, verbose_name='referral fixed amount')),
                ('referral_cap_amount', models.DecimalField(blank=True, decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, null=True, verbose_name='referral cap amount')),
                ('referral_basis', models.CharField(blank=True, choices=[('gross_commission', 'Gross commission income'), ('agent_side_before_fees', 'Agent side before fees'), ('agent_side_after_fees', 'Agent side after fees'), ('fixed_only', 'Fixed amount only')], max_length=32, verbose_name='referral basis')),
                ('referral_notes', models.CharField(blank=True, max_length=500, verbose_name='referral notes')),
                ('special_arrangements', models.TextField(blank=True, verbose_name='special arrangements')),
                ('addenda_references', models.JSONField(blank=True, default=list, help_text='Ordered list of addendum identifiers or titles.', verbose_name='addenda references')),
                ('internal_notes', models.TextField(blank=True, help_text='Broker-only notes. Gated by a separate permission.', verbose_name='internal notes')),
                ('party_snapshot', models.JSONField(blank=True, default=dict, verbose_name='party snapshot')),
                ('office_snapshot', models.JSONField(blank=True, default=dict, verbose_name='office snapshot')),
                ('terms_snapshot', models.JSONField(blank=True, default=dict, verbose_name='terms snapshot')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='viewed at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='signed at')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='activated at')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='superseded at')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='expired at')),
                ('terminated_at', models.DateTimeField(blank=True, null=True, verbose_name='terminated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='contract.agentcontract', verbose_name='amends')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_contracts_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('mentor_payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentor_contracts', to=settings.AUTH_USER_MODEL, verbose_name='mentor payee')),
                ('office', models.ForeignKey(help_text='Office that owns this agreement for scope and mailing.', on_delete=django.db.models.deletion.PROTECT, related_name='agent_contracts', to='user.office', verbose_name='owning office')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_contracts', to=settings.AUTH_USER_MODEL, verbose_name='recipient agent')),
                ('referral_payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_contracts', to=settings.AUTH_USER_MODEL, verbose_name='referral payee')),
                ('root_agreement', models.ForeignKey(blank=True, help_text='First agreement in the family. Null on the root itself.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_versions', to='contract.agentcontract', verbose_name='root agreement')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='contract.agentcontract', verbose_name='supersedes')),
            ],
            options={
                'verbose_name': 'agent contract',
                'verbose_name_plural': 'agent contracts',
                'ordering': ['-effective_on', '-version_number', '-pk'],
                'permissions': (('manage_agent_contracts', 'Can manage scoped agent contracts'), ('view_commission_terms', 'Can view contract commission terms'), ('view_internal_notes', 'Can view contract internal notes')),
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ContractArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('kind', models.CharField(choices=[('generated_pdf', 'Generated PDF'), ('signed_pdf', 'Signed PDF'), ('addendum', 'Addendum'), ('other', 'Other')], max_length=32, verbose_name='kind')),
                ('display_name', models.CharField(help_text='Human-facing filename. Never a storage path or public URL.', max_length=180, verbose_name='display name')),
                ('file', models.FileField(help_text='Protected storage reference. Not a public URL.', max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.contract.models._artifact_upload_to, verbose_name='file')),
                ('media_type', models.CharField(max_length=120, verbose_name='media type')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='size in bytes')),
                ('checksum', models.CharField(help_text='SHA-256 hex digest of the stored bytes.', max_length=64, verbose_name='checksum')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='contract.agentcontract', verbose_name='contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_artifacts_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'contract artifact',
                'verbose_name_plural': 'contract artifacts',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='agentcontract',
            name='generated_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contract.contractartifact', verbose_name='generated PDF'),
        ),
        migrations.AddField(
            model_name='agentcontract',
            name='signed_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contract.contractartifact', verbose_name='signed PDF'),
        ),
        migrations.CreateModel(
            name='ContractTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('version_label', models.CharField(help_text='Semantic version label, e.g. 1.0.0.', max_length=32, verbose_name='version label')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='contract.contracttemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'contract template version',
                'verbose_name_plural': 'contract template versions',
                'ordering': ['template', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentcontract',
            name='template_version',
            field=models.ForeignKey(blank=True, help_text='Originating published template version, when chosen.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contract.contracttemplateversion', verbose_name='template version'),
        ),
        migrations.AddIndex(
            model_name='contractartifact',
            index=models.Index(fields=['contract', 'kind'], name='contract_artifact_kind'),
        ),
        migrations.AddConstraint(
            model_name='contractartifact',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='contract_artifact_has_bytes'),
        ),
        migrations.AddConstraint(
            model_name='contracttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_label'), name='contract_template_version_unique_label'),
        ),
        migrations.AddIndex(
            model_name='agentcontract',
            index=models.Index(fields=['recipient', 'status'], name='contract_recipient_status'),
        ),
        migrations.AddIndex(
            model_name='agentcontract',
            index=models.Index(fields=['office', 'status'], name='contract_office_status'),
        ),
        migrations.AddIndex(
            model_name='agentcontract',
            index=models.Index(fields=['status', '-effective_on'], name='contract_status_effective'),
        ),
        migrations.AddIndex(
            model_name='agentcontract',
            index=models.Index(fields=['family_id', 'version_number'], name='contract_family_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.UniqueConstraint(fields=('family_id', 'version_number'), name='contract_family_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('recipient',), name='contract_one_active_per_recipient'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('expires_on__isnull', True), ('expires_on__gte', models.F('effective_on')), _connector='OR'), name='contract_expires_on_or_after_effective'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='contract_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('agent_split_percent__isnull', True), models.Q(('agent_split_percent__gte', Decimal('0')), ('agent_split_percent__lte', Decimal('100'))), _connector='OR'), name='contract_agent_split_bounds'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('office_split_percent__isnull', True), models.Q(('office_split_percent__gte', Decimal('0')), ('office_split_percent__lte', Decimal('100'))), _connector='OR'), name='contract_office_split_bounds'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('transaction_fee_percent__isnull', True), models.Q(('transaction_fee_percent__gte', Decimal('0')), ('transaction_fee_percent__lte', Decimal('100'))), _connector='OR'), name='contract_txn_fee_percent_bounds'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('mentor_percent__isnull', True), models.Q(('mentor_percent__gte', Decimal('0')), ('mentor_percent__lte', Decimal('100'))), _connector='OR'), name='contract_mentor_percent_bounds'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('referral_percent__isnull', True), models.Q(('referral_percent__gte', Decimal('0')), ('referral_percent__lte', Decimal('100'))), _connector='OR'), name='contract_referral_percent_bounds'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('transaction_fee_amount__isnull', True), ('transaction_fee_amount__gte', Decimal('0')), _connector='OR'), name='contract_txn_fee_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('annual_cap_amount__isnull', True), ('annual_cap_amount__gte', Decimal('0')), _connector='OR'), name='contract_annual_cap_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('mentor_fixed_amount__isnull', True), ('mentor_fixed_amount__gte', Decimal('0')), _connector='OR'), name='contract_mentor_fixed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('mentor_cap_amount__isnull', True), ('mentor_cap_amount__gte', Decimal('0')), _connector='OR'), name='contract_mentor_cap_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('referral_fixed_amount__isnull', True), ('referral_fixed_amount__gte', Decimal('0')), _connector='OR'), name='contract_referral_fixed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('referral_cap_amount__isnull', True), ('referral_cap_amount__gte', Decimal('0')), _connector='OR'), name='contract_referral_cap_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent_split_percent__isnull', True), ('office_split_percent__isnull', True)), models.Q(('agent_split_percent__isnull', False), ('office_split_percent__isnull', False)), _connector='OR'), name='contract_splits_both_or_neither'),
        ),
    ]
