# Generated by Django 6.0.8 on 2026-08-23 16:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_agent_contract_data_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcontract',
            name='calculation_rule_version',
            field=models.CharField(default='1.0.0', help_text='Commission policy version frozen on this contract. Issued calculations use this value so later policy bumps do not silently reinterpret historical terms.', max_length=16, verbose_name='calculation rule version'),
        ),
        migrations.CreateModel(
            name='CommissionCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('rule_version', models.CharField(max_length=16, verbose_name='rule version')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('fingerprint', models.CharField(db_index=True, help_text='SHA-256 of rule version + input + terms snapshots. Identical requests reuse the same row (idempotent).', max_length=64, verbose_name='fingerprint')),
                ('input_snapshot', models.JSONField(default=dict, verbose_name='input snapshot')),
                ('terms_snapshot', models.JSONField(default=dict, verbose_name='terms snapshot')),
                ('intermediate_snapshot', models.JSONField(default=dict, verbose_name='intermediate snapshot')),
                ('result_snapshot', models.JSONField(default=dict, verbose_name='result snapshot')),
                ('explanation', models.JSONField(default=list, help_text='Ordered human-readable lines; mentor and referral labeled separately.', verbose_name='explanation')),
                ('mentor_amount', models.DecimalField(decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, verbose_name='mentor amount')),
                ('referral_amount', models.DecimalField(decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, verbose_name='referral amount')),
                ('agent_net_amount', models.DecimalField(decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, verbose_name='agent net amount')),
                ('office_net_amount', models.DecimalField(decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, verbose_name='office net amount')),
                ('transaction_fee_amount', models.DecimalField(decimal_places=2, help_text='US dollars with cents. Currency: USD. Nonnegative.', max_digits=12, verbose_name='transaction fee amount')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_calculations', to='contract.agentcontract', verbose_name='contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_calculations_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'commission calculation',
                'verbose_name_plural': 'commission calculations',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['contract', '-created_at'], name='contract_calc_contract_time')],
                'constraints': [models.UniqueConstraint(fields=('contract', 'fingerprint'), name='contract_calculation_idempotent')],
            },
        ),
    ]
