# Generated by Django 6.0.8 on 2026-08-24 07:46

import apps.contract.models
import apps.user.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_mentor_referral_commission_calculations'),
        ('user', '0025_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'ordering': ['name'], 'permissions': (('manage_contract_templates', 'Can manage scoped contract template drafts'), ('approve_contract_templates', 'Can approve and activate scoped contract templates')), 'verbose_name': 'contract template', 'verbose_name_plural': 'contract templates'},
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='active_version',
            field=models.ForeignKey(blank=True, help_text='Published version currently active for new contracts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contract.contracttemplateversion', verbose_name='active version'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='applicable_offices',
            field=models.ManyToManyField(blank=True, help_text='Explicit offices this template family applies to.', related_name='contract_templates', to='user.office', verbose_name='applicable offices'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='applicable_regions',
            field=models.ManyToManyField(blank=True, help_text='Region office rows this template family applies to.', related_name='regional_contract_templates', to='user.office', verbose_name='applicable regions'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approved at'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_templates_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='company_wide',
            field=models.BooleanField(default=False, help_text='Applies brokerage-wide instead of a narrower office scope.', verbose_name='company wide'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='effective_from',
            field=models.DateField(blank=True, null=True, verbose_name='effective from'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='effective_until',
            field=models.DateField(blank=True, null=True, verbose_name='effective until'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='jurisdiction_state_codes',
            field=models.JSONField(blank=True, default=list, help_text="Applicable US state codes, e.g. ['VA', 'MD'].", verbose_name='jurisdiction state codes'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retired at'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='retired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_templates_retired', to=settings.AUTH_USER_MODEL, verbose_name='retired by'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_template_versions_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_template_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='display_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='display name'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='extracted_placeholder_keys',
            field=models.JSONField(blank=True, default=list, help_text='Placeholder names parsed from the protected source file.', verbose_name='extracted placeholder keys'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='merge_schema',
            field=models.JSONField(blank=True, default=list, help_text='Allowlisted merge variables and their documented sources.', verbose_name='merge schema'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='preview_checksum',
            field=models.CharField(blank=True, help_text='SHA-256 hex digest of the preview PDF bytes.', max_length=64, verbose_name='preview checksum'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='preview_context',
            field=models.JSONField(blank=True, default=dict, help_text='Synthetic merge values used for the stored preview.', verbose_name='preview context'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='preview_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='preview generated at'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='preview_pdf',
            field=models.FileField(blank=True, help_text='Production-path preview output rendered with synthetic data.', max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.contract.models._template_preview_upload_to, verbose_name='preview PDF'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retired at'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='retired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_template_versions_retired', to=settings.AUTH_USER_MODEL, verbose_name='retired by'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='source_checksum',
            field=models.CharField(blank=True, help_text='SHA-256 hex digest of the uploaded source bytes.', max_length=64, verbose_name='source checksum'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='source_document',
            field=models.FileField(blank=True, help_text='Protected template source file. Never a public URL.', max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.contract.models._template_source_upload_to, verbose_name='source document'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='source_format',
            field=models.CharField(blank=True, help_text='Allowed values are docx and pdf.', max_length=16, verbose_name='source format'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='source_media_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='source media type'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='contract.contracttemplateversion', verbose_name='supersedes'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, help_text='Structured validation failures from the rendering safety pass.', verbose_name='validation errors'),
        ),
    ]
