# Generated by Django 6.0.8 on 2026-08-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contracttemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractartifact',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Page count, validated markers, and other non-PII render facts.', verbose_name='generation metadata'),
        ),
        migrations.AddField(
            model_name='contractartifact',
            name='input_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of frozen snapshots + template source + renderer version. Used for idempotent retries.', max_length=64, verbose_name='input fingerprint'),
        ),
        migrations.AddField(
            model_name='contractartifact',
            name='renderer_version',
            field=models.CharField(blank=True, help_text='PDF renderer/pipeline version that produced this artifact.', max_length=32, verbose_name='renderer version'),
        ),
        migrations.AddField(
            model_name='contractartifact',
            name='rule_version',
            field=models.CharField(blank=True, help_text='Frozen calculation rule version at generation time.', max_length=32, verbose_name='calculation rule version'),
        ),
    ]
