# Generated by Django 6.0.8 on 2026-08-26 02:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contract_artifact_pdf_generation_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSigningIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('contract_version', models.CharField(max_length=64, verbose_name='contract version token')),
                ('artifact_checksum', models.CharField(max_length=64, verbose_name='artifact checksum')),
                ('session_key_hash', models.CharField(max_length=64, verbose_name='session key hash')),
                ('request_ip_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='request IP hash')),
                ('request_ua_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='request user-agent hash')),
                ('disclosure_version', models.CharField(max_length=64, verbose_name='disclosure version')),
                ('consent_accepted_at', models.DateTimeField(verbose_name='consent accepted at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('docuseal_submission_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='DocuSeal submission id')),
                ('docuseal_submitter_slug', models.CharField(blank=True, default='', max_length=120, verbose_name='DocuSeal submitter slug')),
                ('embed_src', models.TextField(blank=True, default='', verbose_name='embed src')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumed at')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_signing_intents', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_intents', to='contract.contractartifact', verbose_name='generated artifact')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_intents', to='contract.agentcontract', verbose_name='contract')),
            ],
            options={
                'verbose_name': 'contract signing intent',
                'verbose_name_plural': 'contract signing intents',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='signed at')),
                ('disclosure_version', models.CharField(max_length=64, verbose_name='disclosure version')),
                ('signature_method', models.CharField(choices=[('docuseal_embedded', 'DocuSeal embedded')], default='docuseal_embedded', max_length=32, verbose_name='signature method')),
                ('docuseal_submission_id', models.PositiveBigIntegerField(unique=True, verbose_name='DocuSeal submission id')),
                ('docuseal_submitter_slug', models.CharField(blank=True, default='', max_length=120, verbose_name='DocuSeal submitter slug')),
                ('request_ip_hash', models.CharField(blank=True, default='', help_text='SHA-256 of client IP at intent start; empty if unavailable.', max_length=64, verbose_name='request IP hash')),
                ('request_ua_hash', models.CharField(blank=True, default='', help_text='SHA-256 of truncated user agent at intent start.', max_length=64, verbose_name='request user-agent hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_records', to='contract.contractartifact', verbose_name='signed artifact')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature_record', to='contract.agentcontract', verbose_name='contract')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_signatures', to=settings.AUTH_USER_MODEL, verbose_name='signer')),
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature', to='contract.contractsigningintent', verbose_name='signing intent')),
            ],
            options={
                'verbose_name': 'contract signature',
                'verbose_name_plural': 'contract signatures',
                'ordering': ['-signed_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='contractsigningintent',
            index=models.Index(fields=['contract', 'status', '-created_at'], name='contract_sign_intent_lookup'),
        ),
    ]
