# Generated by Django 6.0.8 on 2026-08-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contract_signing_intent_and_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcontract',
            name='docuseal_agent_submitter_slug',
            field=models.CharField(blank=True, default='', help_text='Agent role submitter slug for the embedded signing form.', max_length=120, verbose_name='DocuSeal agent submitter slug'),
        ),
        migrations.AddField(
            model_name='agentcontract',
            name='docuseal_submission_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Issue-time DocuSeal submission reused for agent signing.', null=True, unique=True, verbose_name='DocuSeal submission id'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='docuseal_external_id',
            field=models.CharField(blank=True, default='', help_text='Stable hub key mirrored to DocuSeal as external_id.', max_length=120, verbose_name='DocuSeal external id'),
        ),
        migrations.AddField(
            model_name='contracttemplateversion',
            name='docuseal_template_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Remote DocuSeal template used for field placement and signing.', null=True, verbose_name='DocuSeal template id'),
        ),
        migrations.AlterField(
            model_name='contracttemplateversion',
            name='source_format',
            field=models.CharField(blank=True, help_text='Allowed value is pdf (DocuSeal builder).', max_length=16, verbose_name='source format'),
        ),
    ]
