# Generated by Django 6.0.8 on 2026-08-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0006_docuseal_template_builder_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contracttemplateversion",
            name="field_layout",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Hub-placed DocuSeal fields: name, type, role, page, x, y, w, h "
                    "(PDF points at scale 1)."
                ),
                verbose_name="field layout",
            ),
        ),
        migrations.AlterField(
            model_name="contracttemplateversion",
            name="source_format",
            field=models.CharField(
                blank=True,
                help_text="Allowed value is pdf (Hub field placer).",
                max_length=16,
                verbose_name="source format",
            ),
        ),
    ]
