# Generated by Django 6.0.8 on 2026-08-29 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_restore_docuseal_from_opensign'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsignature',
            name='appearance_checksum',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the signature appearance bytes applied to the PDF.', max_length=64, verbose_name='signature appearance checksum'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='certificate_of_completion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completion_certificate_for', to='contract.contractartifact', verbose_name='certificate of completion'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='seal_cert_fingerprint',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the org sealing certificate DER bytes.', max_length=64, verbose_name='org seal certificate fingerprint'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='seal_cert_subject',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='org seal certificate subject'),
        ),
        migrations.AlterField(
            model_name='contractartifact',
            name='kind',
            field=models.CharField(choices=[('generated_pdf', 'Generated PDF'), ('signed_pdf', 'Signed PDF'), ('certificate_of_completion', 'Certificate of completion'), ('addendum', 'Addendum'), ('other', 'Other')], max_length=32, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='docuseal_submission_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='legacy DocuSeal submission id'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='docuseal_submitter_slug',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='legacy DocuSeal submitter slug'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='signature_method',
            field=models.CharField(choices=[('hub_embedded', 'Hub embedded'), ('docuseal_embedded', 'DocuSeal embedded (legacy)')], default='hub_embedded', max_length=32, verbose_name='signature method'),
        ),
        migrations.AlterField(
            model_name='contractsigningintent',
            name='docuseal_submission_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='legacy DocuSeal submission id'),
        ),
        migrations.AlterField(
            model_name='contractsigningintent',
            name='docuseal_submitter_slug',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='legacy DocuSeal submitter slug'),
        ),
        migrations.AlterField(
            model_name='contractsigningintent',
            name='embed_src',
            field=models.TextField(blank=True, default='', help_text='Unused for Hub-native signing; retained for historical rows.', verbose_name='legacy embed src'),
        ),
    ]
