# Generated by Django 6.0.8 on 2026-08-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_hub_native_signing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplateversion',
            name='field_layout',
            field=models.JSONField(blank=True, default=list, help_text='Hub-placed fields: name, type, role, page, x, y, w, h (PDF points at scale 1).', verbose_name='field layout'),
        ),
    ]
