# Generated by Django 6.0.8 on 2026-08-30 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_alter_field_layout_help_text'),
        ('user', '0027_feedback_triage_role_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcontract',
            name='change_kind',
            field=models.CharField(choices=[('original', 'Original agreement'), ('amendment', 'Amendment'), ('addendum', 'Addendum'), ('replacement', 'Replacement')], db_index=True, default='original', help_text='Why this family version exists: original, amendment/addendum, or full replacement. Never rewrite a signed original in place.', max_length=32, verbose_name='change kind'),
        ),
        migrations.AddField(
            model_name='agentcontract',
            name='change_summary',
            field=models.TextField(blank=True, help_text='Legal narrative for an amendment or addendum: what changes and effective-date implications. Empty on originals and most replacements.', verbose_name='change summary'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('change_kind__in', ['amendment', 'addendum']), _negated=True), ('amends__isnull', False), _connector='OR'), name='contract_amendment_requires_amends'),
        ),
        migrations.AddConstraint(
            model_name='agentcontract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('change_kind', 'replacement'), _negated=True), ('supersedes__isnull', False), _connector='OR'), name='contract_replacement_requires_supersedes'),
        ),
    ]
