# Generated by Django 6.0.8 on 2026-08-30 11:13

import apps.contract.models
import apps.user.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_contract_versioning_and_amendments'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsignature',
            name='agent_text_values',
            field=models.JSONField(blank=True, default=dict, help_text='Optional Agent text/checkbox values applied during finalization.', verbose_name='agent text values'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='appearance_file',
            field=models.FileField(blank=True, default='', help_text='Protected PNG/JPEG used to stamp Agent signature fields.', max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.contract.models._signature_appearance_upload_to, verbose_name='signature appearance'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='finalization_error',
            field=models.CharField(blank=True, default='', help_text='Non-PII outcome code when final PDF generation fails.', max_length=64, verbose_name='finalization error code'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='finalization_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16, verbose_name='finalization status'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='generation_task_id',
            field=models.CharField(blank=True, default='', help_text='Celery task identity for the latest finalization attempt.', max_length=255, verbose_name='generation task id'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='initials_file',
            field=models.FileField(blank=True, default='', max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.contract.models._signature_initials_upload_to, verbose_name='initials appearance'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='signed_date_value',
            field=models.CharField(blank=True, default='', help_text='Date text stamped onto Agent date fields during finalization.', max_length=64, verbose_name='signed date value'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='source_checksum',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the issued/reviewed PDF bytes used as signing input. Final generation must bind to this checksum, never re-render terms.', max_length=64, verbose_name='source review PDF checksum'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='artifact',
            field=models.ForeignKey(blank=True, help_text='Authoritative final signed PDF once generation succeeds. Null while finalization is pending or failed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signature_records', to='contract.contractartifact', verbose_name='signed artifact'),
        ),
    ]
