# Generated by Django 6.0.8 on 2026-09-10 08:37

import apps.contract.models
import apps.user.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_signed_pdf_finalization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcontract',
            name='company_signatory',
            field=models.ForeignKey(blank=True, help_text='Named officer who must complete the Company ceremony before the agent can sign. Required at issue.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_signatory_contracts', to=settings.AUTH_USER_MODEL, verbose_name='company signatory'),
        ),
        migrations.AddField(
            model_name='agentcontract',
            name='company_signed_at',
            field=models.DateTimeField(blank=True, help_text='When the named company signatory completed their ceremony.', null=True, verbose_name='company signed at'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='signer_role',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Company', 'Company')], db_index=True, default='Agent', max_length=16, verbose_name='signer role'),
        ),
        migrations.AddField(
            model_name='contractsigningintent',
            name='signer_role',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Company', 'Company')], db_index=True, default='Agent', max_length=16, verbose_name='signer role'),
        ),
        migrations.AlterField(
            model_name='agentcontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for review'), ('awaiting_company_signature', 'Awaiting company signature'), ('sent', 'Sent to agent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('active', 'Active'), ('superseded', 'Superseded'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('generation_error', 'Generation error')], db_index=True, default='draft', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='agent_text_values',
            field=models.JSONField(blank=True, default=dict, help_text='Optional text/checkbox values applied during finalization.', verbose_name='signer text values'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='appearance_file',
            field=models.FileField(blank=True, default='', help_text="Protected PNG/JPEG used to stamp this role's signature fields.", max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.contract.models._signature_appearance_upload_to, verbose_name='signature appearance'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='artifact',
            field=models.ForeignKey(blank=True, help_text='Authoritative final signed PDF once generation succeeds. Null while finalization is pending or failed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_signature_records', to='contract.contractartifact', verbose_name='signed artifact'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_records', to='contract.agentcontract', verbose_name='contract'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='signed_date_value',
            field=models.CharField(blank=True, default='', help_text="Date text stamped onto this role's date fields during finalization.", max_length=64, verbose_name='signed date value'),
        ),
        migrations.AddConstraint(
            model_name='contractsignature',
            constraint=models.UniqueConstraint(fields=('contract', 'signer_role'), name='contract_one_signature_per_role'),
        ),
    ]
