# Generated by Django 6.0.8 on 2026-09-10 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_company_countersign'),
        ('user', '0029_office_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentcontract',
            index=models.Index(fields=['company_signatory', 'status'], name='contract_company_signature'),
        ),
    ]
