# Generated by Django 6.0.8 on 2026-08-30 01:56

import apps.it_support.models
import apps.user.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0027_feedback_triage_role_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('reference', models.CharField(blank=True, max_length=16, unique=True, verbose_name='reference')),
                ('subject', models.CharField(max_length=160, verbose_name='subject')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('login_account', 'Login / Account'), ('microsoft_365', 'Microsoft 365 / Email'), ('intranet', 'Intranet'), ('computer_device', 'Computer / Device'), ('printer', 'Printer'), ('network_wifi', 'Network / Wi-Fi'), ('software', 'Software'), ('permissions_access', 'Permissions / Access'), ('agent_onboarding', 'New agent setup'), ('other', 'Other')], max_length=32, verbose_name='category')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='location')),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In progress'), ('waiting_user', 'Waiting for your reply'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='status')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Urgent'), (2, 'High'), (3, 'Normal'), (4, 'Low')], default=3, verbose_name='priority')),
                ('preferred_contact', models.CharField(choices=[('hub', 'In the hub'), ('email', 'Email'), ('phone', 'Phone call'), ('teams', 'Microsoft Teams')], default='hub', max_length=16, verbose_name='preferred contact')),
                ('device_info', models.CharField(blank=True, max_length=300, verbose_name='device / browser')),
                ('page_url', models.CharField(blank=True, max_length=2000, verbose_name='page')),
                ('submission_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='submission key')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('about_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_about_me', to=settings.AUTH_USER_MODEL, verbose_name='about')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='user.office', verbose_name='office')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
            ],
            options={
                'verbose_name': 'support ticket',
                'verbose_name_plural': 'support tickets',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('file', models.FileField(max_length=255, storage=apps.user.storage.private_storage, upload_to=apps.it_support.models.attachment_upload_to, verbose_name='file')),
                ('display_name', models.CharField(max_length=200, verbose_name='display name')),
                ('media_type', models.CharField(blank=True, max_length=100, verbose_name='media type')),
                ('byte_size', models.PositiveBigIntegerField(default=0, verbose_name='size in bytes')),
                ('internal', models.BooleanField(default=False, verbose_name='internal only')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='it_support.supportticket', verbose_name='ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'ticket attachment',
                'verbose_name_plural': 'ticket attachments',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('body', models.TextField(verbose_name='body')),
                ('internal', models.BooleanField(default=False, help_text='IT-only. Never shown to the requester.', verbose_name='internal only')),
                ('is_resolution', models.BooleanField(default=False, verbose_name='resolution note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_replies', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='it_support.supportticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket reply',
                'verbose_name_plural': 'ticket replies',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority'], name='its_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['office', 'status'], name='its_office_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assignee', 'status'], name='its_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['submitter', 'status'], name='its_submitter_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category'], name='its_category_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['submission_key'], name='its_submission_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', False), ('status__in', ['closed'])), models.Q(models.Q(('status__in', ['closed']), _negated=True), ('closed_at__isnull', True)), _connector='OR'), name='it_support_closed_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='supportticket',
            constraint=models.CheckConstraint(condition=models.Q(('subject', ''), _negated=True), name='it_support_requires_subject'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['ticket', 'internal'], name='its_att_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketreply',
            index=models.Index(fields=['ticket', 'internal', 'created_at'], name='its_reply_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketreply',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='it_support_reply_requires_body'),
        ),
        migrations.AddConstraint(
            model_name='ticketreply',
            constraint=models.CheckConstraint(condition=models.Q(('internal', True), ('is_resolution', True), _negated=True), name='it_support_resolution_is_not_internal'),
        ),
    ]
