from django.urls import path

from apps.contract.views.administration_views import (
    contract_template_action,
    contract_template_builder_saved,
    contract_template_create,
    contract_template_docuseal_source,
    contract_template_update,
    contract_template_workspace,
)
from apps.contract.views.agent_contract_views import (
    agent_contract_artifact_download,
    agent_contract_create,
    agent_contract_lifecycle,
    agent_contract_new,
    agent_contract_preview,
    agent_contract_recipient_search,
    agent_contract_template_options,
    agent_contract_update,
    agent_contract_validate,
    agent_contract_workspace,
)
from apps.contract.views.my_contract_views import (
    my_contract,
    my_contract_artifact_preview,
)
from apps.contract.views.signing_views import (
    docuseal_contract_webhook,
    my_contract_sign,
    my_contract_sign_status,
)

urlpatterns = [
    path("my-contract", my_contract, name="my_contract"),
    path("my-contract/sign", my_contract_sign, name="my_contract_sign"),
    path(
        "my-contract/sign/status",
        my_contract_sign_status,
        name="my_contract_sign_status",
    ),
    path(
        "my-contract/<uuid:public_id>/artifacts/<uuid:artifact_public_id>/preview",
        my_contract_artifact_preview,
        name="my_contract_artifact_preview",
    ),
    path(
        "webhooks/docuseal/contracts",
        docuseal_contract_webhook,
        name="docuseal_contract_webhook",
    ),
    path(
        "operations/contract-templates/templates/create",
        contract_template_create,
        name="contract_template_create",
    ),
    path(
        "operations/contract-templates/templates/<int:version_id>",
        contract_template_workspace,
        name="contract_template_workspace",
    ),
    path(
        "operations/contract-templates/templates/<int:version_id>/save",
        contract_template_update,
        name="contract_template_update",
    ),
    path(
        "operations/contract-templates/templates/<int:version_id>/action",
        contract_template_action,
        name="contract_template_action",
    ),
    path(
        "operations/contract-templates/templates/<int:version_id>/builder-saved",
        contract_template_builder_saved,
        name="contract_template_builder_saved",
    ),
    path(
        "operations/contract-templates/docuseal-source/<str:token>",
        contract_template_docuseal_source,
        name="contract_template_docuseal_source",
    ),
    path(
        "operations/agent-contracts/new",
        agent_contract_new,
        name="agent_contract_new",
    ),
    path(
        "operations/agent-contracts/create",
        agent_contract_create,
        name="agent_contract_create",
    ),
    path(
        "operations/agent-contracts/recipients",
        agent_contract_recipient_search,
        name="agent_contract_recipient_search",
    ),
    path(
        "operations/agent-contracts/template-options",
        agent_contract_template_options,
        name="agent_contract_template_options",
    ),
    path(
        "operations/agent-contracts/<uuid:public_id>",
        agent_contract_workspace,
        name="agent_contract_workspace",
    ),
    path(
        "operations/agent-contracts/<uuid:public_id>/save",
        agent_contract_update,
        name="agent_contract_update",
    ),
    path(
        "operations/agent-contracts/<uuid:public_id>/lifecycle",
        agent_contract_lifecycle,
        name="agent_contract_lifecycle",
    ),
    path(
        "operations/agent-contracts/<uuid:public_id>/validate",
        agent_contract_validate,
        name="agent_contract_validate",
    ),
    path(
        "operations/agent-contracts/<uuid:public_id>/preview",
        agent_contract_preview,
        name="agent_contract_preview",
    ),
    path(
        "operations/agent-contracts/<uuid:public_id>/artifacts/"
        "<uuid:artifact_public_id>/download",
        agent_contract_artifact_download,
        name="agent_contract_artifact_download",
    ),
]
