# Generated by Django 6.0.8 on 2026-08-19 09:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='event name')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='schema version')),
                ('actor_id', models.CharField(blank=True, max_length=255, verbose_name='actor')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('organization_id', models.CharField(blank=True, max_length=255, verbose_name='organisation')),
                ('correlation_id', models.UUIDField(blank=True, null=True, verbose_name='correlation ID')),
                ('causation_id', models.UUIDField(blank=True, null=True, verbose_name='causation ID')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='occurred at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='dispatched at')),
            ],
            options={
                'verbose_name': 'domain event',
                'verbose_name_plural': 'domain events',
                'ordering': ['-occurred_at'],
                'permissions': [('can_replay_events', 'Can replay / retry domain events')],
                'indexes': [models.Index(fields=['status', 'occurred_at'], name='audit_de_status_occurred'), models.Index(fields=['name', 'occurred_at'], name='audit_de_name_occurred')],
            },
        ),
        migrations.CreateModel(
            name='EventDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer', models.CharField(db_index=True, max_length=120, verbose_name='consumer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead', 'Dead')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='next attempt at')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='audit.domainevent', verbose_name='event')),
            ],
            options={
                'verbose_name': 'event delivery',
                'verbose_name_plural': 'event deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='audit_delivery_status_next')],
                'constraints': [models.UniqueConstraint(fields=('event', 'consumer'), name='audit_delivery_unique_event_consumer')],
            },
        ),
    ]
