# Generated by Django 6.0.8 on 2026-08-19 10:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_version', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='payload version')),
                ('action', models.CharField(db_index=True, max_length=120, verbose_name='action')),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('service', 'Service'), ('anonymous', 'Anonymous')], db_index=True, default='user', max_length=16, verbose_name='actor type')),
                ('actor_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='actor ID')),
                ('actor_label', models.CharField(blank=True, max_length=255, verbose_name='actor label')),
                ('actor_snapshot', models.JSONField(default=dict, verbose_name='actor snapshot')),
                ('impersonated_by', models.JSONField(blank=True, default=dict, verbose_name='impersonated by')),
                ('target_type', models.CharField(db_index=True, max_length=120, verbose_name='target type')),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='target ID')),
                ('target_label', models.CharField(blank=True, max_length=255, verbose_name='target label')),
                ('target_snapshot', models.JSONField(default=dict, verbose_name='target snapshot')),
                ('organization_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='organization ID')),
                ('office_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='office ID')),
                ('region_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='region ID')),
                ('source', models.CharField(db_index=True, default='app', max_length=64, verbose_name='source')),
                ('channel', models.CharField(blank=True, max_length=64, verbose_name='channel')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='request ID')),
                ('correlation_id', models.UUIDField(blank=True, null=True, verbose_name='correlation ID')),
                ('remote_addr', models.CharField(blank=True, max_length=128, verbose_name='remote address')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('failure', 'Failure')], db_index=True, default='success', max_length=16, verbose_name='outcome')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('before', models.JSONField(blank=True, default=dict, verbose_name='before')),
                ('after', models.JSONField(blank=True, default=dict, verbose_name='after')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='occurred at')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-occurred_at', '-recorded_at'],
                'permissions': [('can_view_audit_events', 'Can view audit events'), ('can_export_audit_events', 'Can export audit events')],
                'indexes': [models.Index(fields=['occurred_at'], name='audit_ae_occurred'), models.Index(fields=['actor_type', 'actor_id'], name='audit_ae_actor'), models.Index(fields=['action', 'occurred_at'], name='audit_ae_action'), models.Index(fields=['target_type', 'target_id'], name='audit_ae_target'), models.Index(fields=['organization_id', 'occurred_at'], name='audit_ae_org'), models.Index(fields=['office_id', 'occurred_at'], name='audit_ae_office'), models.Index(fields=['region_id', 'occurred_at'], name='audit_ae_region'), models.Index(fields=['request_id'], name='audit_ae_request')],
            },
        ),
    ]
