import type { LucideIcon } from "lucide-react";
import {
  ArrowLeftRight,
  BookOpen,
  Boxes,
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  ChartColumn,
  ClipboardList,
  DoorOpen,
  FileStack,
  FileText,
  FileUser,
  FolderOpen,
  GraduationCap,
  Headphones,
  Landmark,
  LayoutDashboard,
  ListTodo,
  Megaphone,
  MessageSquareText,
  Shield,
  ShieldCheck,
  UserCog,
  UserPlus,
  UserRoundSearch,
  Users,
  Warehouse,
  Wrench,
} from "lucide-react";

import { hasPermission, type PermissionCheck } from "@/lib/permissions";
import { getRoleCatalogEntry } from "@/lib/roles";
import { routes } from "@/lib/routes";
import type { HubFeatures, PrimaryOffice, User } from "@/types";

/** Bump when persisted expansion semantics or registry identity changes. */
export const HUB_NAV_VERSION = 1;
export const HUB_NAV_EXPANSION_STORAGE_KEY = `onest-hub-nav:v${HUB_NAV_VERSION}:expanded`;

export type HubNavGroupKey =
  | "general"
  | "tools"
  | "my-office"
  | "directory"
  | "administration";

export type HubNavSectionKey =
  | "admin-people"
  | "admin-reporting"
  | "admin-operations"
  | "admin-content"
  | "admin-governance-support";

/** Compile-time proof that registry route names exist in the generated map. */
export type HubNavRouteName = keyof typeof routes;

export interface HubNavRoute {
  /** Stable Django route identifier. */
  name: HubNavRouteName;
  /** Generated by `routes`; registry consumers never concatenate paths. */
  href: string;
}

export interface HubNavActiveMatch {
  /** Paths that activate the item, including their detail descendants. */
  prefixes: string[];
  /** More-specific sibling paths that belong to another item. */
  exclusions?: string[];
}

export interface HubNavItem {
  /** Stable registry identity; never derived from copy. */
  key: string;
  label: string;
  route: HubNavRoute;
  icon: LucideIcon;
  group: HubNavGroupKey;
  order: number;
  access: "authenticated" | "permission-protected";
  /** Effective permission requirements. Both `any` and `all` are supported. */
  permissions: PermissionCheck;
  /**
   * Role codes this destination is *relevant* to. Absent means everyone.
   *
   * This is presentation, not authorization, and the two must not be confused:
   *
   * - It can only ever **hide** an entry. It never reveals one, and a hidden
   *   route is exactly as reachable as it was before.
   * - It is legal only on items that require no permissions. Where a
   *   permission exists it already expresses relevance, and adding a role
   *   filter on top would hide a destination somebody was deliberately
   *   granted. `validateHubNavRegistry` enforces this.
   * - A superuser is never filtered by it.
   *
   * Authorization stays where it belongs: `permissions` here, and
   * `enforce_policy` on the view.
   */
  roles?: readonly string[];
  /**
   * Copy-only relabeling for the roles the destination reads differently to.
   * Like `roles`, this is presentation: it changes wording, never visibility,
   * reachability, or authorization. Matching is on stable role codes, and a
   * superuser is not special-cased — the label follows the roles a person
   * actually holds.
   */
  labelForRoles?: { roles: readonly string[]; label: string };
  /** Missing keys hide; explicit false keys render a protected Soon route. */
  feature?: string;
  requiresOffice?: boolean;
  activeMatch: HubNavActiveMatch;
  /** Optional nested/collapsible administrative structure. */
  section?: HubNavSectionKey;
}

export interface HubNavGroupDefinition {
  key: HubNavGroupKey;
  label: string;
  order: number;
}

export interface HubNavSectionDefinition {
  key: HubNavSectionKey;
  label: string;
  group: HubNavGroupKey;
  order: number;
  defaultExpanded: boolean;
}

export interface ResolvedHubNavGroup extends HubNavGroupDefinition {
  items: ResolvedHubNavItem[];
}

export interface ResolvedHubNavSection extends HubNavSectionDefinition {
  items: ResolvedHubNavItem[];
}

export interface ResolvedHubNavItem extends HubNavItem {
  availability: "available" | "coming-soon";
}

function route(name: HubNavRouteName, href: string): HubNavRoute {
  return { name, href };
}

function active(...prefixes: string[]): HubNavActiveMatch {
  return { prefixes };
}

export const HUB_NAV_GROUPS: HubNavGroupDefinition[] = [
  { key: "general", label: "General", order: 10 },
  { key: "tools", label: "Tools", order: 20 },
  { key: "my-office", label: "My office", order: 30 },
  { key: "directory", label: "Directory", order: 40 },
  { key: "administration", label: "Administration", order: 50 },
];

export const HUB_NAV_SECTIONS: HubNavSectionDefinition[] = [
  {
    key: "admin-people",
    label: "People",
    group: "administration",
    order: 10,
    defaultExpanded: true,
  },
  {
    key: "admin-reporting",
    label: "Reporting",
    group: "administration",
    order: 15,
    defaultExpanded: true,
  },
  {
    key: "admin-operations",
    label: "Operations",
    group: "administration",
    order: 20,
    defaultExpanded: true,
  },
  {
    key: "admin-content",
    label: "Content",
    group: "administration",
    order: 30,
    defaultExpanded: true,
  },
  {
    key: "admin-governance-support",
    label: "Governance & support",
    group: "administration",
    order: 40,
    defaultExpanded: true,
  },
];

/**
 * Licensed roles that carry their own listings and their own brokerage
 * agreement. "My contract" and "Agent transactions" describe a book of
 * business; to a coordinator, an accountant, or IT they are two permanent
 * dead ends in the rail.
 *
 * Someone who is both a manager and a producing agent holds both codes, so
 * they keep the entries. Adjusting who counts is an edit to this array.
 */
const PRODUCING_ROLES = [
  "realtor",
  "branch_manager",
  "regional_manager",
  "principal_broker",
  "broker_admin",
] as const;

/** Producers, plus the roles that prepare and hand out listing collateral. */
const MARKETING_ROLES = [
  ...PRODUCING_ROLES,
  "marketing_team",
  "branch_admin",
  "regional_admin",
] as const;

/**
 * Version-controlled navigation configuration shared by the desktop rail and
 * mobile drawer. Ordering is data, not array position, and every destination
 * declares its authorization mode and active matching behavior.
 */
export const HUB_NAV_REGISTRY: HubNavItem[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    route: route("dashboard", routes.dashboard()),
    icon: LayoutDashboard,
    group: "general",
    order: 10,
    access: "authenticated",
    permissions: {},
    activeMatch: active(routes.dashboard()),
  },
  {
    key: "announcements",
    label: "Announcements",
    route: route("announcements", routes.announcements()),
    icon: Megaphone,
    group: "general",
    order: 15,
    access: "authenticated",
    permissions: {},
    feature: "announcements",
    activeMatch: active(routes.announcements()),
  },
  {
    key: "agent-profile",
    label: "Your profile",
    route: route("profile", routes.profile()),
    icon: Briefcase,
    group: "general",
    order: 20,
    access: "authenticated",
    permissions: {},
    // Same page, same fields. A licensed producer reads it as their public
    // agent record; everyone else reads it as their own staff profile.
    labelForRoles: { roles: PRODUCING_ROLES, label: "Agent profile" },
    activeMatch: active(routes.profile()),
  },
  {
    key: "my-tools",
    label: "My tools",
    route: route("my_tools", routes.my_tools()),
    icon: Wrench,
    group: "general",
    order: 25,
    access: "authenticated",
    permissions: {},
    feature: "my-tools",
    activeMatch: active(routes.my_tools()),
  },
  {
    key: "my-contract",
    label: "My contract",
    route: route("my_contract", routes.my_contract()),
    icon: FileText,
    group: "general",
    order: 30,
    access: "authenticated",
    permissions: {},
    roles: PRODUCING_ROLES,
    feature: "my-contract",
    activeMatch: active(routes.my_contract()),
  },
  {
    key: "agent-transactions",
    label: "Agent transactions",
    route: route("coming_soon", routes.coming_soon("agent-transactions")),
    icon: ClipboardList,
    group: "general",
    order: 40,
    access: "authenticated",
    permissions: {},
    roles: PRODUCING_ROLES,
    feature: "agent-transactions",
    activeMatch: active(routes.coming_soon("agent-transactions")),
  },
  {
    key: "my-reservations",
    label: "My reservations",
    route: route("my_reservations", routes.my_reservations()),
    icon: CalendarDays,
    group: "general",
    order: 50,
    access: "authenticated",
    permissions: {},
    feature: "my-reservations",
    activeMatch: active(routes.my_reservations()),
  },
  {
    key: "training-learning",
    label: "Training & learning",
    route: route("training_learning", routes.training_learning()),
    icon: BookOpen,
    group: "tools",
    order: 10,
    access: "authenticated",
    permissions: {},
    feature: "training-learning",
    activeMatch: active(routes.training_learning()),
  },
  {
    key: "documents-forms",
    label: "Documents & forms",
    route: route("coming_soon", routes.coming_soon("documents-forms")),
    icon: FolderOpen,
    group: "tools",
    order: 20,
    access: "authenticated",
    permissions: {},
    feature: "documents-forms",
    activeMatch: active(routes.coming_soon("documents-forms")),
  },
  {
    key: "marketing-resources",
    label: "Marketing resources",
    route: route("marketing_resources", routes.marketing_resources()),
    icon: Megaphone,
    group: "tools",
    order: 30,
    access: "authenticated",
    permissions: {},
    roles: MARKETING_ROLES,
    feature: "marketing-resources",
    activeMatch: active(routes.marketing_resources()),
  },
  {
    key: "policies-compliance",
    label: "Policies & compliance",
    route: route("coming_soon", routes.coming_soon("policies-compliance")),
    icon: Shield,
    group: "tools",
    order: 40,
    access: "authenticated",
    permissions: {},
    feature: "policies-compliance",
    activeMatch: active(routes.coming_soon("policies-compliance")),
  },
  {
    key: "office-info",
    label: "Office info",
    route: route("office_info", routes.office_info()),
    icon: Landmark,
    group: "my-office",
    order: 10,
    access: "authenticated",
    permissions: {},
    feature: "office-info",
    requiresOffice: true,
    activeMatch: active(routes.office_info()),
  },
  {
    key: "office-resources",
    label: "Office resources",
    route: route("office_resources", routes.office_resources()),
    icon: Boxes,
    group: "my-office",
    order: 20,
    access: "authenticated",
    permissions: {},
    feature: "office-resources",
    requiresOffice: true,
    activeMatch: active(routes.office_resources()),
  },
  {
    key: "office-inventory",
    label: "Office inventory",
    route: route("office_inventory", routes.office_inventory()),
    icon: Building2,
    group: "my-office",
    order: 30,
    access: "authenticated",
    permissions: {},
    feature: "office-inventory",
    requiresOffice: true,
    activeMatch: active(routes.office_inventory()),
  },
  {
    key: "room-availability",
    label: "Room availability",
    route: route("room_availability", routes.room_availability()),
    icon: CalendarRange,
    group: "my-office",
    order: 40,
    access: "permission-protected",
    permissions: { all: ["reservations.book_spaces"] },
    feature: "room-availability",
    activeMatch: active(routes.room_availability()),
  },
  {
    key: "agent-directory",
    label: "Agent directory",
    route: route("agent_directory", routes.agent_directory()),
    icon: Users,
    group: "directory",
    order: 10,
    access: "authenticated",
    permissions: {},
    feature: "agent-directory",
    activeMatch: active(routes.agent_directory()),
  },
  {
    key: "admin-users",
    label: "Users",
    route: route("admin_users", routes.admin_users()),
    icon: Users,
    group: "administration",
    section: "admin-people",
    order: 10,
    access: "permission-protected",
    permissions: { all: ["web.view_users"] },
    feature: "admin-users",
    activeMatch: {
      prefixes: [routes.admin_users()],
      exclusions: [routes.admin_add_user()],
    },
  },
  {
    key: "admin-new-agents",
    label: "New Agent List",
    route: route("admin_new_agents", routes.admin_new_agents()),
    icon: UserRoundSearch,
    group: "administration",
    section: "admin-people",
    order: 20,
    access: "permission-protected",
    permissions: { all: ["web.view_new_agents"] },
    feature: "admin-new-agents",
    activeMatch: active(routes.admin_new_agents()),
  },
  {
    key: "admin-add-user",
    label: "Add New User",
    route: route("admin_add_user", routes.admin_add_user()),
    icon: UserPlus,
    group: "administration",
    section: "admin-people",
    order: 30,
    access: "permission-protected",
    permissions: { all: ["web.add_users"] },
    feature: "admin-add-user",
    activeMatch: active(routes.admin_add_user()),
  },
  {
    key: "admin-assign-roles",
    label: "Assign User Roles",
    route: route("admin_assign_roles", routes.admin_assign_roles()),
    icon: UserCog,
    group: "administration",
    section: "admin-people",
    order: 40,
    access: "permission-protected",
    permissions: { all: ["web.assign_user_roles"] },
    feature: "admin-assign-roles",
    activeMatch: active(routes.admin_assign_roles()),
  },
  {
    key: "admin-agent-contracts",
    label: "Agent Contracts",
    route: route("admin_agent_contracts", routes.admin_agent_contracts()),
    icon: FileUser,
    group: "administration",
    section: "admin-people",
    order: 50,
    access: "permission-protected",
    permissions: { all: ["web.view_agent_contracts"] },
    feature: "admin-agent-contracts",
    activeMatch: active(routes.admin_agent_contracts()),
  },
  {
    key: "admin-contract-templates",
    label: "Contract Templates",
    route: route("admin_contract_templates", routes.admin_contract_templates()),
    icon: FileStack,
    group: "administration",
    section: "admin-people",
    order: 55,
    access: "permission-protected",
    permissions: { all: ["contract.manage_contract_templates"] },
    feature: "admin-contract-templates",
    activeMatch: active(routes.admin_contract_templates()),
  },
  {
    key: "reports",
    label: "Reports",
    route: route("report_catalog", routes.report_catalog()),
    icon: ChartColumn,
    group: "administration",
    section: "admin-reporting",
    order: 10,
    access: "permission-protected",
    permissions: { all: ["web.view_reports"] },
    feature: "reports",
    activeMatch: active(routes.report_catalog()),
  },
  {
    key: "admin-transactions",
    label: "Transactions",
    route: route("admin_transactions", routes.admin_transactions()),
    icon: ArrowLeftRight,
    group: "administration",
    section: "admin-operations",
    order: 10,
    access: "permission-protected",
    permissions: { all: ["web.view_transactions"] },
    feature: "admin-transactions",
    activeMatch: active(routes.admin_transactions()),
  },
  {
    key: "admin-inventory",
    label: "Inventory",
    route: route("admin_inventory", routes.admin_inventory()),
    icon: Warehouse,
    group: "administration",
    section: "admin-operations",
    order: 20,
    access: "permission-protected",
    permissions: { all: ["web.view_inventory"] },
    feature: "admin-inventory",
    activeMatch: active(routes.admin_inventory()),
  },
  {
    key: "admin-reservations",
    label: "Reservations",
    route: route("admin_reservations", routes.admin_reservations()),
    icon: CalendarCheck,
    group: "administration",
    section: "admin-operations",
    order: 30,
    access: "permission-protected",
    permissions: { all: ["web.view_reservations"] },
    feature: "admin-reservations",
    activeMatch: active(routes.admin_reservations()),
  },
  {
    key: "admin-rooms",
    label: "Rooms",
    route: route("space_administration", routes.space_administration()),
    icon: DoorOpen,
    group: "administration",
    section: "admin-operations",
    order: 40,
    access: "permission-protected",
    permissions: { all: ["reservations.view_spaces"] },
    feature: "admin-rooms",
    activeMatch: active(routes.space_administration()),
  },
  {
    key: "admin-announcements",
    label: "Announcements",
    route: route("admin_announcements", routes.admin_announcements()),
    icon: Megaphone,
    group: "administration",
    section: "admin-content",
    order: 10,
    access: "permission-protected",
    permissions: { all: ["web.manage_announcements"] },
    feature: "admin-announcements",
    activeMatch: active(routes.admin_announcements()),
  },
  {
    key: "admin-training",
    label: "Training",
    route: route("admin_training", routes.admin_training()),
    icon: GraduationCap,
    group: "administration",
    section: "admin-content",
    order: 20,
    access: "permission-protected",
    permissions: { all: ["web.manage_training"] },
    feature: "admin-training",
    activeMatch: active(routes.admin_training()),
  },
  {
    key: "admin-marketing-resources",
    label: "Marketing Resources",
    route: route("admin_marketing_resources", routes.admin_marketing_resources()),
    icon: Megaphone,
    group: "administration",
    section: "admin-content",
    order: 25,
    access: "permission-protected",
    permissions: { all: ["web.manage_marketing_resources"] },
    feature: "admin-marketing-resources",
    activeMatch: active(routes.admin_marketing_resources()),
  },
  {
    key: "admin-documents",
    label: "Documents",
    route: route("admin_documents", routes.admin_documents()),
    icon: FolderOpen,
    group: "administration",
    section: "admin-content",
    order: 30,
    access: "permission-protected",
    permissions: { all: ["web.manage_documents"] },
    feature: "admin-documents",
    activeMatch: active(routes.admin_documents()),
  },
  {
    key: "admin-compliance",
    label: "Compliance",
    route: route("admin_compliance", routes.admin_compliance()),
    icon: ShieldCheck,
    group: "administration",
    section: "admin-governance-support",
    order: 10,
    access: "permission-protected",
    permissions: { all: ["web.view_compliance"] },
    feature: "admin-compliance",
    activeMatch: active(routes.admin_compliance()),
  },
  {
    key: "admin-feedback",
    label: "Feedback",
    route: route("admin_feedback", routes.admin_feedback()),
    icon: MessageSquareText,
    group: "administration",
    section: "admin-governance-support",
    order: 20,
    access: "permission-protected",
    permissions: { all: ["web.view_feedback"] },
    feature: "admin-feedback",
    activeMatch: active(routes.admin_feedback()),
  },
  {
    key: "admin-platform-tasks",
    label: "Platform Tasks",
    route: route("admin_platform_tasks", routes.admin_platform_tasks()),
    icon: ListTodo,
    group: "administration",
    section: "admin-governance-support",
    order: 30,
    access: "permission-protected",
    permissions: { all: ["web.view_platform_tasks"] },
    feature: "admin-platform-tasks",
    activeMatch: active(routes.admin_platform_tasks()),
  },
  {
    key: "admin-office-resources",
    label: "Office Resources",
    route: route("admin_office_resources", routes.admin_office_resources()),
    icon: Boxes,
    group: "administration",
    section: "admin-governance-support",
    order: 35,
    access: "permission-protected",
    permissions: { all: ["web.view_office_resources_admin"] },
    feature: "admin-office-resources",
    activeMatch: {
      prefixes: [routes.admin_office_resources()],
      exclusions: [routes.admin_office_resource_new()],
    },
  },
  {
    key: "admin-offices",
    label: "Offices",
    route: route("admin_offices", routes.admin_offices()),
    icon: Building2,
    group: "administration",
    section: "admin-governance-support",
    order: 40,
    access: "permission-protected",
    permissions: { all: ["web.manage_offices"] },
    feature: "admin-offices",
    activeMatch: active(routes.admin_offices()),
  },
  {
    key: "admin-it-support",
    label: "IT Support",
    route: route("admin_it_support", routes.admin_it_support()),
    icon: Headphones,
    group: "administration",
    section: "admin-governance-support",
    order: 50,
    access: "permission-protected",
    permissions: { all: ["web.view_it_support"] },
    feature: "admin-it-support",
    activeMatch: active(routes.admin_it_support()),
  },
  {
    key: "admin-tool-catalog",
    label: "Tool catalog",
    route: route("onboarding_tool_catalog", routes.onboarding_tool_catalog()),
    icon: Wrench,
    group: "administration",
    section: "admin-governance-support",
    order: 175,
    access: "permission-protected",
    permissions: { all: ["web.manage_onboarding_tools"] },
    feature: "admin-tool-catalog",
    activeMatch: active(routes.onboarding_tool_catalog()),
  },
];

export const HUB_ADMIN_NAV = HUB_NAV_REGISTRY.filter(
  (item) => item.group === "administration",
);

export const HUB_FEATURE_KEYS = HUB_NAV_REGISTRY.flatMap((item) =>
  item.feature ? [item.feature] : [],
);

function normalizedPath(value: string): string {
  const path = value.split(/[?#]/)[0] || "/";
  return path.length > 1 ? path.replace(/\/+$/, "") : path;
}

function pathMatches(current: string, prefix: string): boolean {
  const path = normalizedPath(current);
  const candidate = normalizedPath(prefix);
  return path === candidate || path.startsWith(`${candidate}/`);
}

export function isHubNavItemActive(item: HubNavItem, current: string): boolean {
  if (item.activeMatch.exclusions?.some((path) => pathMatches(current, path))) {
    return false;
  }
  return item.activeMatch.prefixes.some((path) => pathMatches(current, path));
}

export function hubNavItemDescription(item: ResolvedHubNavItem): string | null {
  return item.availability === "coming-soon" ? `${item.label} is coming soon` : null;
}

function hasDeclaredPermissions(item: HubNavItem): boolean {
  return Boolean(item.permissions.all?.length || item.permissions.any?.length);
}

/**
 * Whether a destination is worth showing this reader.
 *
 * Only ever narrows, and only for items that ask for no permission — see
 * `HubNavItem.roles`. A superuser is exempt so a platform administrator can
 * still reach every destination from the rail.
 */
function isRelevantToRoles(user: User, item: HubNavItem): boolean {
  if (!item.roles || user.isSuperuser) {
    return true;
  }
  if (!Array.isArray(user.roles)) {
    return false;
  }
  return item.roles.some((code) => user.roles.includes(code));
}

/** Registry copy, swapped for the roles that read the destination differently. */
function labelFor(user: User, item: HubNavItem): string {
  const override = item.labelForRoles;
  if (!override || !Array.isArray(user.roles)) {
    return item.label;
  }
  return override.roles.some((code) => user.roles.includes(code))
    ? override.label
    : item.label;
}

/** Return human-readable contract violations without mutating the registry. */
export function validateHubNavRegistry(
  registry: HubNavItem[] = HUB_NAV_REGISTRY,
  groups: HubNavGroupDefinition[] = HUB_NAV_GROUPS,
  sections: HubNavSectionDefinition[] = HUB_NAV_SECTIONS,
): string[] {
  const errors: string[] = [];
  const groupKeys = new Set<HubNavGroupKey>();
  const groupOrders = new Set<number>();
  for (const group of groups) {
    if (groupKeys.has(group.key)) {
      errors.push(`duplicate group key: ${group.key}`);
    }
    if (groupOrders.has(group.order)) {
      errors.push(`duplicate group order: ${group.order}`);
    }
    groupKeys.add(group.key);
    groupOrders.add(group.order);
  }

  const sectionKeys = new Set<HubNavSectionKey>();
  const sectionOrders = new Set<string>();
  for (const section of sections) {
    if (sectionKeys.has(section.key)) {
      errors.push(`duplicate section key: ${section.key}`);
    }
    if (!groupKeys.has(section.group)) {
      errors.push(`unknown section group for ${section.key}: ${section.group}`);
    }
    const scopedOrder = `${section.group}:${section.order}`;
    if (sectionOrders.has(scopedOrder)) {
      errors.push(`duplicate section order: ${scopedOrder}`);
    }
    sectionKeys.add(section.key);
    sectionOrders.add(scopedOrder);
  }

  const sectionByKey = new Map(sections.map((section) => [section.key, section]));
  const seenKeys = new Set<string>();
  const seenDestinations = new Set<string>();
  const seenOrders = new Set<string>();

  for (const item of registry) {
    if (seenKeys.has(item.key)) {
      errors.push(`duplicate item key: ${item.key}`);
    }
    seenKeys.add(item.key);

    const destination = normalizedPath(item.route.href);
    if (seenDestinations.has(destination)) {
      errors.push(`duplicate destination: ${destination}`);
    }
    seenDestinations.add(destination);

    if (!groupKeys.has(item.group)) {
      errors.push(`unknown group for ${item.key}: ${item.group}`);
    }
    if (!item.route.href.startsWith("/")) {
      errors.push(`invalid route for ${item.key}: ${item.route.href}`);
    }
    if (item.order < 0 || !Number.isInteger(item.order)) {
      errors.push(`invalid order for ${item.key}: ${item.order}`);
    }
    const orderScope = `${item.group}:${item.section ?? "root"}:${item.order}`;
    if (seenOrders.has(orderScope)) {
      errors.push(`duplicate order: ${orderScope}`);
    }
    seenOrders.add(orderScope);

    if (item.access === "permission-protected" && !hasDeclaredPermissions(item)) {
      errors.push(`protected item lacks permissions: ${item.key}`);
    }
    if (item.roles) {
      if (item.roles.length === 0) {
        // An empty list would hide the entry from everyone, which is a
        // deletion written as a filter.
        errors.push(`item declares an empty role list: ${item.key}`);
      }
      if (hasDeclaredPermissions(item)) {
        // Relevance may not double as authorization. See `HubNavItem.roles`.
        errors.push(`permission-protected item declares roles: ${item.key}`);
      }
      for (const code of item.roles) {
        if (!getRoleCatalogEntry(code)) {
          errors.push(`unknown role for ${item.key}: ${code}`);
        }
      }
    }
    if (item.labelForRoles) {
      if (item.labelForRoles.roles.length === 0) {
        errors.push(`item declares an empty label role list: ${item.key}`);
      }
      if (!item.labelForRoles.label.trim()) {
        errors.push(`item declares an empty role label: ${item.key}`);
      }
      for (const code of item.labelForRoles.roles) {
        if (!getRoleCatalogEntry(code)) {
          errors.push(`unknown label role for ${item.key}: ${code}`);
        }
      }
    }
    if (item.activeMatch.prefixes.length === 0) {
      errors.push(`item lacks active match prefixes: ${item.key}`);
    }
    if (item.section) {
      const section = sectionByKey.get(item.section);
      if (!section || section.group !== item.group) {
        errors.push(`invalid section for ${item.key}: ${item.section}`);
      }
    }
  }
  return errors;
}

/**
 * Permission and availability resolver used by every visual navigation mode.
 * Unknown permissions, missing feature keys, and required context fail closed.
 * Explicit false features remain protected Soon entries. Dedupe is by both
 * registry key and destination so aliases cannot leak in.
 */
export function resolveHubNav(
  user: User | null,
  features: HubFeatures = {},
  primaryOffice: PrimaryOffice | null = null,
  registry: HubNavItem[] = HUB_NAV_REGISTRY,
  groups: HubNavGroupDefinition[] = HUB_NAV_GROUPS,
): ResolvedHubNavGroup[] {
  if (!user || !Array.isArray(user.permissions)) {
    return [];
  }

  const seenKeys = new Set<string>();
  const seenDestinations = new Set<string>();
  const visible: ResolvedHubNavItem[] = registry
    .filter((item) => {
      const destination = normalizedPath(item.route.href);
      if (seenKeys.has(item.key) || seenDestinations.has(destination)) {
        return false;
      }
      if (!hasPermission(user, item.permissions)) {
        return false;
      }
      if (!isRelevantToRoles(user, item)) {
        return false;
      }
      if (item.feature !== undefined && features[item.feature] === undefined) {
        return false;
      }
      if (item.requiresOffice && primaryOffice === null) {
        return false;
      }
      seenKeys.add(item.key);
      seenDestinations.add(destination);
      return true;
    })
    .map((item) => ({
      ...item,
      label: labelFor(user, item),
      availability:
        item.feature !== undefined && features[item.feature] === false
          ? ("coming-soon" as const)
          : ("available" as const),
    }))
    .sort(
      (left, right) => left.order - right.order || left.key.localeCompare(right.key),
    );

  return [...groups]
    .sort((left, right) => left.order - right.order)
    .map((group) => ({
      ...group,
      items: visible
        .filter((item) => item.group === group.key)
        .sort(
          (left, right) =>
            sectionOrder(left.section) - sectionOrder(right.section) ||
            left.order - right.order ||
            left.key.localeCompare(right.key),
        ),
    }))
    .filter((group) => group.items.length > 0);
}

/**
 * Split a resolved rail into the destinations that work and the ones that do
 * not yet.
 *
 * Registered-but-unbuilt modules stay visible to authorized readers — that is
 * a deliberate product decision, so people can see what is coming. Scattering
 * them through the groups was the problem: an agent's rail was fourteen
 * entries of which eight went nowhere, and two whole headings ("Tools",
 * "Directory") contained nothing else. A reader learning the product cannot
 * tell the shape of what they have from a list that is mostly promises.
 *
 * Gathering them into one disclosure keeps the promise and gives the rail back
 * its meaning: every heading now names live work, and what is coming is one
 * countable row somebody can open on purpose.
 *
 * A group left with no live items disappears. Permission filtering is
 * untouched — a pending item a reader may not hold never reaches either half.
 */
export function partitionByAvailability(groups: ResolvedHubNavGroup[]): {
  live: ResolvedHubNavGroup[];
  pending: ResolvedHubNavItem[];
} {
  const pending: ResolvedHubNavItem[] = [];
  const live: ResolvedHubNavGroup[] = [];

  for (const group of groups) {
    const available = group.items.filter((item) => {
      if (item.availability === "coming-soon") {
        pending.push(item);
        return false;
      }
      return true;
    });
    if (available.length > 0) {
      live.push({ ...group, items: available });
    }
  }
  return { live, pending };
}

function sectionOrder(key: HubNavSectionKey | undefined): number {
  if (!key) {
    return -1;
  }
  return HUB_NAV_SECTIONS.find((section) => section.key === key)?.order ?? 0;
}

export function resolveHubNavSections(
  group: ResolvedHubNavGroup,
  sections: HubNavSectionDefinition[] = HUB_NAV_SECTIONS,
): ResolvedHubNavSection[] {
  return sections
    .filter((section) => section.group === group.key)
    .sort((left, right) => left.order - right.order)
    .map((section) => ({
      ...section,
      items: group.items.filter((item) => item.section === section.key),
    }))
    .filter((section) => section.items.length > 0);
}

/**
 * Read only known section keys from storage. Corrupt/missing state falls back
 * to reviewed defaults; stale keys from older deployments are ignored.
 */
export function parseHubNavExpansion(
  stored: string | null,
  allowedSections: HubNavSectionDefinition[] = HUB_NAV_SECTIONS,
): Set<HubNavSectionKey> {
  const allowed = new Set(allowedSections.map((section) => section.key));
  const defaults = new Set(
    allowedSections
      .filter((section) => section.defaultExpanded)
      .map((section) => section.key),
  );
  if (stored === null) {
    return defaults;
  }
  try {
    const value: unknown = JSON.parse(stored);
    if (!Array.isArray(value) || !value.every((item) => typeof item === "string")) {
      return defaults;
    }
    return new Set(
      value.filter((item): item is HubNavSectionKey =>
        allowed.has(item as HubNavSectionKey),
      ),
    );
  } catch {
    return defaults;
  }
}
