# Generated by Django 6.0.8 on 2026-08-21 18:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('notification_type', models.CharField(choices=[('contract', 'Contracts'), ('transaction', 'Transactions'), ('announcement', 'Announcements'), ('training', 'Training'), ('inventory', 'Inventory'), ('room', 'Rooms'), ('lead', 'Leads'), ('administrative', 'Administration'), ('account', 'Your account')], db_index=True, max_length=32, verbose_name='type')),
                ('event_key', models.CharField(max_length=120, verbose_name='event')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Normal'), (4, 'Low')], default=3, verbose_name='priority')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Must be acknowledged individually; excluded from mark-all-read and cannot be archived while unread.', verbose_name='mandatory')),
                ('source_module', models.CharField(blank=True, max_length=64, verbose_name='source module')),
                ('source_record_type', models.CharField(blank=True, max_length=64, verbose_name='source record')),
                ('source_record_id', models.CharField(blank=True, max_length=64, verbose_name='source record id')),
                ('action_key', models.CharField(blank=True, max_length=64, verbose_name='action')),
                ('action_args', models.JSONField(blank=True, default=list, verbose_name='action arguments')),
                ('dedupe_key', models.CharField(help_text='Unique per recipient; a replayed producer creates nothing.', max_length=200, verbose_name='idempotency key')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='available from')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-available_at', '-pk'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'archived_at', 'available_at'], name='notif_recipient_unread'), models.Index(fields=['recipient', 'archived_at', 'available_at'], name='notif_recipient_inbox'), models.Index(fields=['recipient', 'notification_type', 'available_at'], name='notif_recipient_type'), models.Index(fields=['recipient', 'priority', 'available_at'], name='notif_recipient_priority')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='notif_recipient_dedupe'), models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('available_at')), _connector='OR'), name='notif_expiry_after_availability')],
            },
        ),
    ]
