# Generated by Django 6.0.8 on 2026-08-21 19:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.JSONField(blank=True, default=dict, help_text='Explicit choices only, as {channel: {category: bool}}. Absent entries follow the category default.', verbose_name='channel choices')),
                ('policy_version', models.PositiveSmallIntegerField(default=1, verbose_name='policy version')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('channel', models.CharField(default='email', max_length=16, verbose_name='channel')),
                ('delivery_key', models.CharField(help_text="The notification's idempotency key; unique per channel.", max_length=200, verbose_name='delivery key')),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('suppressed', 'Suppressed'), ('failed', 'Failed — will retry'), ('dead', 'Failed — gave up')], default='pending', max_length=16, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('suppression_reason', models.CharField(blank=True, max_length=64, verbose_name='suppression reason')),
                ('to_email', models.EmailField(blank=True, max_length=254, verbose_name='sent to')),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='queued at')),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='first attempt at')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='last attempt at')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='next attempt at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification', verbose_name='notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification delivery',
                'verbose_name_plural': 'notification deliveries',
                'ordering': ['-queued_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notif_email_due'), models.Index(fields=['status', 'queued_at'], name='notif_email_backlog'), models.Index(fields=['recipient', 'status'], name='notif_email_recipient')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'channel', 'delivery_key'), name='notif_email_recipient_key')],
            },
        ),
    ]
