# Generated by Django 6.0.8 on 2026-08-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference_notificationemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='policy_version',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='policy version'),
        ),
    ]
